// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// AssistenciaTecnicaCausas is an object representing the database table.
type AssistenciaTecnicaCausas struct {
	AtcID        int    `boil:"atc_id" json:"atc_id" toml:"atc_id" yaml:"atc_id"`
	AtrID        int    `boil:"atr_id" json:"atr_id" toml:"atr_id" yaml:"atr_id"`
	AtcDescricao string `boil:"atc_descricao" json:"atc_descricao" toml:"atc_descricao" yaml:"atc_descricao"`
	AtcSituacao  int    `boil:"atc_situacao" json:"atc_situacao" toml:"atc_situacao" yaml:"atc_situacao"`

	R *assistenciaTecnicaCausasR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L assistenciaTecnicaCausasL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AssistenciaTecnicaCausasColumns = struct {
	AtcID        string
	AtrID        string
	AtcDescricao string
	AtcSituacao  string
}{
	AtcID:        "atc_id",
	AtrID:        "atr_id",
	AtcDescricao: "atc_descricao",
	AtcSituacao:  "atc_situacao",
}

var AssistenciaTecnicaCausasTableColumns = struct {
	AtcID        string
	AtrID        string
	AtcDescricao string
	AtcSituacao  string
}{
	AtcID:        "assistencia_tecnica_causas.atc_id",
	AtrID:        "assistencia_tecnica_causas.atr_id",
	AtcDescricao: "assistencia_tecnica_causas.atc_descricao",
	AtcSituacao:  "assistencia_tecnica_causas.atc_situacao",
}

// Generated where

var AssistenciaTecnicaCausasWhere = struct {
	AtcID        whereHelperint
	AtrID        whereHelperint
	AtcDescricao whereHelperstring
	AtcSituacao  whereHelperint
}{
	AtcID:        whereHelperint{field: "`assistencia_tecnica_causas`.`atc_id`"},
	AtrID:        whereHelperint{field: "`assistencia_tecnica_causas`.`atr_id`"},
	AtcDescricao: whereHelperstring{field: "`assistencia_tecnica_causas`.`atc_descricao`"},
	AtcSituacao:  whereHelperint{field: "`assistencia_tecnica_causas`.`atc_situacao`"},
}

// AssistenciaTecnicaCausasRels is where relationship names are stored.
var AssistenciaTecnicaCausasRels = struct {
	Atr string
}{
	Atr: "Atr",
}

// assistenciaTecnicaCausasR is where relationships are stored.
type assistenciaTecnicaCausasR struct {
	Atr *AssistenciaTecnicaResponsavel `boil:"Atr" json:"Atr" toml:"Atr" yaml:"Atr"`
}

// NewStruct creates a new relationship struct
func (*assistenciaTecnicaCausasR) NewStruct() *assistenciaTecnicaCausasR {
	return &assistenciaTecnicaCausasR{}
}

func (r *assistenciaTecnicaCausasR) GetAtr() *AssistenciaTecnicaResponsavel {
	if r == nil {
		return nil
	}
	return r.Atr
}

// assistenciaTecnicaCausasL is where Load methods for each relationship are stored.
type assistenciaTecnicaCausasL struct{}

var (
	assistenciaTecnicaCausasAllColumns            = []string{"atc_id", "atr_id", "atc_descricao", "atc_situacao"}
	assistenciaTecnicaCausasColumnsWithoutDefault = []string{"atc_id", "atr_id", "atc_descricao", "atc_situacao"}
	assistenciaTecnicaCausasColumnsWithDefault    = []string{}
	assistenciaTecnicaCausasPrimaryKeyColumns     = []string{"atc_id"}
	assistenciaTecnicaCausasGeneratedColumns      = []string{}
)

type (
	// AssistenciaTecnicaCausasSlice is an alias for a slice of pointers to AssistenciaTecnicaCausas.
	// This should almost always be used instead of []AssistenciaTecnicaCausas.
	AssistenciaTecnicaCausasSlice []*AssistenciaTecnicaCausas
	// AssistenciaTecnicaCausasHook is the signature for custom AssistenciaTecnicaCausas hook methods
	AssistenciaTecnicaCausasHook func(context.Context, boil.ContextExecutor, *AssistenciaTecnicaCausas) error

	assistenciaTecnicaCausasQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	assistenciaTecnicaCausasType                 = reflect.TypeOf(&AssistenciaTecnicaCausas{})
	assistenciaTecnicaCausasMapping              = queries.MakeStructMapping(assistenciaTecnicaCausasType)
	assistenciaTecnicaCausasPrimaryKeyMapping, _ = queries.BindMapping(assistenciaTecnicaCausasType, assistenciaTecnicaCausasMapping, assistenciaTecnicaCausasPrimaryKeyColumns)
	assistenciaTecnicaCausasInsertCacheMut       sync.RWMutex
	assistenciaTecnicaCausasInsertCache          = make(map[string]insertCache)
	assistenciaTecnicaCausasUpdateCacheMut       sync.RWMutex
	assistenciaTecnicaCausasUpdateCache          = make(map[string]updateCache)
	assistenciaTecnicaCausasUpsertCacheMut       sync.RWMutex
	assistenciaTecnicaCausasUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var assistenciaTecnicaCausasAfterSelectMu sync.Mutex
var assistenciaTecnicaCausasAfterSelectHooks []AssistenciaTecnicaCausasHook

var assistenciaTecnicaCausasBeforeInsertMu sync.Mutex
var assistenciaTecnicaCausasBeforeInsertHooks []AssistenciaTecnicaCausasHook
var assistenciaTecnicaCausasAfterInsertMu sync.Mutex
var assistenciaTecnicaCausasAfterInsertHooks []AssistenciaTecnicaCausasHook

var assistenciaTecnicaCausasBeforeUpdateMu sync.Mutex
var assistenciaTecnicaCausasBeforeUpdateHooks []AssistenciaTecnicaCausasHook
var assistenciaTecnicaCausasAfterUpdateMu sync.Mutex
var assistenciaTecnicaCausasAfterUpdateHooks []AssistenciaTecnicaCausasHook

var assistenciaTecnicaCausasBeforeDeleteMu sync.Mutex
var assistenciaTecnicaCausasBeforeDeleteHooks []AssistenciaTecnicaCausasHook
var assistenciaTecnicaCausasAfterDeleteMu sync.Mutex
var assistenciaTecnicaCausasAfterDeleteHooks []AssistenciaTecnicaCausasHook

var assistenciaTecnicaCausasBeforeUpsertMu sync.Mutex
var assistenciaTecnicaCausasBeforeUpsertHooks []AssistenciaTecnicaCausasHook
var assistenciaTecnicaCausasAfterUpsertMu sync.Mutex
var assistenciaTecnicaCausasAfterUpsertHooks []AssistenciaTecnicaCausasHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AssistenciaTecnicaCausas) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AssistenciaTecnicaCausas) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AssistenciaTecnicaCausas) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AssistenciaTecnicaCausas) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AssistenciaTecnicaCausas) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AssistenciaTecnicaCausas) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AssistenciaTecnicaCausas) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AssistenciaTecnicaCausas) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AssistenciaTecnicaCausas) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range assistenciaTecnicaCausasAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAssistenciaTecnicaCausasHook registers your hook function for all future operations.
func AddAssistenciaTecnicaCausasHook(hookPoint boil.HookPoint, assistenciaTecnicaCausasHook AssistenciaTecnicaCausasHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		assistenciaTecnicaCausasAfterSelectMu.Lock()
		assistenciaTecnicaCausasAfterSelectHooks = append(assistenciaTecnicaCausasAfterSelectHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		assistenciaTecnicaCausasBeforeInsertMu.Lock()
		assistenciaTecnicaCausasBeforeInsertHooks = append(assistenciaTecnicaCausasBeforeInsertHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		assistenciaTecnicaCausasAfterInsertMu.Lock()
		assistenciaTecnicaCausasAfterInsertHooks = append(assistenciaTecnicaCausasAfterInsertHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		assistenciaTecnicaCausasBeforeUpdateMu.Lock()
		assistenciaTecnicaCausasBeforeUpdateHooks = append(assistenciaTecnicaCausasBeforeUpdateHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		assistenciaTecnicaCausasAfterUpdateMu.Lock()
		assistenciaTecnicaCausasAfterUpdateHooks = append(assistenciaTecnicaCausasAfterUpdateHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		assistenciaTecnicaCausasBeforeDeleteMu.Lock()
		assistenciaTecnicaCausasBeforeDeleteHooks = append(assistenciaTecnicaCausasBeforeDeleteHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		assistenciaTecnicaCausasAfterDeleteMu.Lock()
		assistenciaTecnicaCausasAfterDeleteHooks = append(assistenciaTecnicaCausasAfterDeleteHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		assistenciaTecnicaCausasBeforeUpsertMu.Lock()
		assistenciaTecnicaCausasBeforeUpsertHooks = append(assistenciaTecnicaCausasBeforeUpsertHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		assistenciaTecnicaCausasAfterUpsertMu.Lock()
		assistenciaTecnicaCausasAfterUpsertHooks = append(assistenciaTecnicaCausasAfterUpsertHooks, assistenciaTecnicaCausasHook)
		assistenciaTecnicaCausasAfterUpsertMu.Unlock()
	}
}

// One returns a single assistenciaTecnicaCausas record from the query.
func (q assistenciaTecnicaCausasQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AssistenciaTecnicaCausas, error) {
	o := &AssistenciaTecnicaCausas{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for assistencia_tecnica_causas")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AssistenciaTecnicaCausas records from the query.
func (q assistenciaTecnicaCausasQuery) All(ctx context.Context, exec boil.ContextExecutor) (AssistenciaTecnicaCausasSlice, error) {
	var o []*AssistenciaTecnicaCausas

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AssistenciaTecnicaCausas slice")
	}

	if len(assistenciaTecnicaCausasAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AssistenciaTecnicaCausas records in the query.
func (q assistenciaTecnicaCausasQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count assistencia_tecnica_causas rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q assistenciaTecnicaCausasQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if assistencia_tecnica_causas exists")
	}

	return count > 0, nil
}

// Atr pointed to by the foreign key.
func (o *AssistenciaTecnicaCausas) Atr(mods ...qm.QueryMod) assistenciaTecnicaResponsavelQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`atr_id` = ?", o.AtrID),
	}

	queryMods = append(queryMods, mods...)

	return AssistenciaTecnicaResponsavels(queryMods...)
}

// LoadAtr allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (assistenciaTecnicaCausasL) LoadAtr(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAssistenciaTecnicaCausas interface{}, mods queries.Applicator) error {
	var slice []*AssistenciaTecnicaCausas
	var object *AssistenciaTecnicaCausas

	if singular {
		var ok bool
		object, ok = maybeAssistenciaTecnicaCausas.(*AssistenciaTecnicaCausas)
		if !ok {
			object = new(AssistenciaTecnicaCausas)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAssistenciaTecnicaCausas)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAssistenciaTecnicaCausas))
			}
		}
	} else {
		s, ok := maybeAssistenciaTecnicaCausas.(*[]*AssistenciaTecnicaCausas)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAssistenciaTecnicaCausas)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAssistenciaTecnicaCausas))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &assistenciaTecnicaCausasR{}
		}
		args[object.AtrID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &assistenciaTecnicaCausasR{}
			}

			args[obj.AtrID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`assistencia_tecnica_responsavel`),
		qm.WhereIn(`assistencia_tecnica_responsavel.atr_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AssistenciaTecnicaResponsavel")
	}

	var resultSlice []*AssistenciaTecnicaResponsavel
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AssistenciaTecnicaResponsavel")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for assistencia_tecnica_responsavel")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for assistencia_tecnica_responsavel")
	}

	if len(assistenciaTecnicaResponsavelAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Atr = foreign
		if foreign.R == nil {
			foreign.R = &assistenciaTecnicaResponsavelR{}
		}
		foreign.R.AtrAssistenciaTecnicaCausas = append(foreign.R.AtrAssistenciaTecnicaCausas, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AtrID == foreign.AtrID {
				local.R.Atr = foreign
				if foreign.R == nil {
					foreign.R = &assistenciaTecnicaResponsavelR{}
				}
				foreign.R.AtrAssistenciaTecnicaCausas = append(foreign.R.AtrAssistenciaTecnicaCausas, local)
				break
			}
		}
	}

	return nil
}

// SetAtr of the assistenciaTecnicaCausas to the related item.
// Sets o.R.Atr to related.
// Adds o to related.R.AtrAssistenciaTecnicaCausas.
func (o *AssistenciaTecnicaCausas) SetAtr(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AssistenciaTecnicaResponsavel) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `assistencia_tecnica_causas` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"atr_id"}),
		strmangle.WhereClause("`", "`", 0, assistenciaTecnicaCausasPrimaryKeyColumns),
	)
	values := []interface{}{related.AtrID, o.AtcID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AtrID = related.AtrID
	if o.R == nil {
		o.R = &assistenciaTecnicaCausasR{
			Atr: related,
		}
	} else {
		o.R.Atr = related
	}

	if related.R == nil {
		related.R = &assistenciaTecnicaResponsavelR{
			AtrAssistenciaTecnicaCausas: AssistenciaTecnicaCausasSlice{o},
		}
	} else {
		related.R.AtrAssistenciaTecnicaCausas = append(related.R.AtrAssistenciaTecnicaCausas, o)
	}

	return nil
}

// AssistenciaTecnicaCausas retrieves all the records using an executor.
func AssistenciaTecnicaCausas(mods ...qm.QueryMod) assistenciaTecnicaCausasQuery {
	mods = append(mods, qm.From("`assistencia_tecnica_causas`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`assistencia_tecnica_causas`.*"})
	}

	return assistenciaTecnicaCausasQuery{q}
}

// FindAssistenciaTecnicaCausas retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAssistenciaTecnicaCausas(ctx context.Context, exec boil.ContextExecutor, atcID int, selectCols ...string) (*AssistenciaTecnicaCausas, error) {
	assistenciaTecnicaCausasObj := &AssistenciaTecnicaCausas{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `assistencia_tecnica_causas` where `atc_id`=?", sel,
	)

	q := queries.Raw(query, atcID)

	err := q.Bind(ctx, exec, assistenciaTecnicaCausasObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from assistencia_tecnica_causas")
	}

	if err = assistenciaTecnicaCausasObj.doAfterSelectHooks(ctx, exec); err != nil {
		return assistenciaTecnicaCausasObj, err
	}

	return assistenciaTecnicaCausasObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AssistenciaTecnicaCausas) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no assistencia_tecnica_causas provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(assistenciaTecnicaCausasColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	assistenciaTecnicaCausasInsertCacheMut.RLock()
	cache, cached := assistenciaTecnicaCausasInsertCache[key]
	assistenciaTecnicaCausasInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			assistenciaTecnicaCausasAllColumns,
			assistenciaTecnicaCausasColumnsWithDefault,
			assistenciaTecnicaCausasColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(assistenciaTecnicaCausasType, assistenciaTecnicaCausasMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(assistenciaTecnicaCausasType, assistenciaTecnicaCausasMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `assistencia_tecnica_causas` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `assistencia_tecnica_causas` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `assistencia_tecnica_causas` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, assistenciaTecnicaCausasPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into assistencia_tecnica_causas")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.AtcID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for assistencia_tecnica_causas")
	}

CacheNoHooks:
	if !cached {
		assistenciaTecnicaCausasInsertCacheMut.Lock()
		assistenciaTecnicaCausasInsertCache[key] = cache
		assistenciaTecnicaCausasInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AssistenciaTecnicaCausas.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AssistenciaTecnicaCausas) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	assistenciaTecnicaCausasUpdateCacheMut.RLock()
	cache, cached := assistenciaTecnicaCausasUpdateCache[key]
	assistenciaTecnicaCausasUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			assistenciaTecnicaCausasAllColumns,
			assistenciaTecnicaCausasPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update assistencia_tecnica_causas, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `assistencia_tecnica_causas` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, assistenciaTecnicaCausasPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(assistenciaTecnicaCausasType, assistenciaTecnicaCausasMapping, append(wl, assistenciaTecnicaCausasPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update assistencia_tecnica_causas row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for assistencia_tecnica_causas")
	}

	if !cached {
		assistenciaTecnicaCausasUpdateCacheMut.Lock()
		assistenciaTecnicaCausasUpdateCache[key] = cache
		assistenciaTecnicaCausasUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q assistenciaTecnicaCausasQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for assistencia_tecnica_causas")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for assistencia_tecnica_causas")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AssistenciaTecnicaCausasSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), assistenciaTecnicaCausasPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `assistencia_tecnica_causas` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, assistenciaTecnicaCausasPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in assistenciaTecnicaCausas slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all assistenciaTecnicaCausas")
	}
	return rowsAff, nil
}

var mySQLAssistenciaTecnicaCausasUniqueColumns = []string{
	"atc_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AssistenciaTecnicaCausas) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no assistencia_tecnica_causas provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(assistenciaTecnicaCausasColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLAssistenciaTecnicaCausasUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	assistenciaTecnicaCausasUpsertCacheMut.RLock()
	cache, cached := assistenciaTecnicaCausasUpsertCache[key]
	assistenciaTecnicaCausasUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			assistenciaTecnicaCausasAllColumns,
			assistenciaTecnicaCausasColumnsWithDefault,
			assistenciaTecnicaCausasColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			assistenciaTecnicaCausasAllColumns,
			assistenciaTecnicaCausasPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert assistencia_tecnica_causas, could not build update column list")
		}

		ret := strmangle.SetComplement(assistenciaTecnicaCausasAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`assistencia_tecnica_causas`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `assistencia_tecnica_causas` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(assistenciaTecnicaCausasType, assistenciaTecnicaCausasMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(assistenciaTecnicaCausasType, assistenciaTecnicaCausasMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for assistencia_tecnica_causas")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(assistenciaTecnicaCausasType, assistenciaTecnicaCausasMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for assistencia_tecnica_causas")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for assistencia_tecnica_causas")
	}

CacheNoHooks:
	if !cached {
		assistenciaTecnicaCausasUpsertCacheMut.Lock()
		assistenciaTecnicaCausasUpsertCache[key] = cache
		assistenciaTecnicaCausasUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AssistenciaTecnicaCausas record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AssistenciaTecnicaCausas) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AssistenciaTecnicaCausas provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), assistenciaTecnicaCausasPrimaryKeyMapping)
	sql := "DELETE FROM `assistencia_tecnica_causas` WHERE `atc_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from assistencia_tecnica_causas")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for assistencia_tecnica_causas")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q assistenciaTecnicaCausasQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no assistenciaTecnicaCausasQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from assistencia_tecnica_causas")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for assistencia_tecnica_causas")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AssistenciaTecnicaCausasSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(assistenciaTecnicaCausasBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), assistenciaTecnicaCausasPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `assistencia_tecnica_causas` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, assistenciaTecnicaCausasPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from assistenciaTecnicaCausas slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for assistencia_tecnica_causas")
	}

	if len(assistenciaTecnicaCausasAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AssistenciaTecnicaCausas) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAssistenciaTecnicaCausas(ctx, exec, o.AtcID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AssistenciaTecnicaCausasSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AssistenciaTecnicaCausasSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), assistenciaTecnicaCausasPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `assistencia_tecnica_causas`.* FROM `assistencia_tecnica_causas` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, assistenciaTecnicaCausasPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AssistenciaTecnicaCausasSlice")
	}

	*o = slice

	return nil
}

// AssistenciaTecnicaCausasExists checks if the AssistenciaTecnicaCausas row exists.
func AssistenciaTecnicaCausasExists(ctx context.Context, exec boil.ContextExecutor, atcID int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `assistencia_tecnica_causas` where `atc_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, atcID)
	}
	row := exec.QueryRowContext(ctx, sql, atcID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if assistencia_tecnica_causas exists")
	}

	return exists, nil
}

// Exists checks if the AssistenciaTecnicaCausas row exists.
func (o *AssistenciaTecnicaCausas) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AssistenciaTecnicaCausasExists(ctx, exec, o.AtcID)
}
