// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBancos(t *testing.T) {
	t.Parallel()

	query := Bancos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBancosDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBancosQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Bancos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBancosSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BancoSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBancosExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BancoExists(ctx, tx, o.BanID)
	if err != nil {
		t.Errorf("Unable to check if Banco exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BancoExists to return true, but got false.")
	}
}

func testBancosFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	bancoFound, err := FindBanco(ctx, tx, o.BanID)
	if err != nil {
		t.Error(err)
	}

	if bancoFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBancosBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Bancos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBancosOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Bancos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBancosAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	bancoOne := &Banco{}
	bancoTwo := &Banco{}
	if err = randomize.Struct(seed, bancoOne, bancoDBTypes, false, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}
	if err = randomize.Struct(seed, bancoTwo, bancoDBTypes, false, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bancoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bancoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Bancos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBancosCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	bancoOne := &Banco{}
	bancoTwo := &Banco{}
	if err = randomize.Struct(seed, bancoOne, bancoDBTypes, false, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}
	if err = randomize.Struct(seed, bancoTwo, bancoDBTypes, false, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bancoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bancoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func bancoBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func bancoAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Banco) error {
	*o = Banco{}
	return nil
}

func testBancosHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Banco{}
	o := &Banco{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, bancoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Banco object: %s", err)
	}

	AddBancoHook(boil.BeforeInsertHook, bancoBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	bancoBeforeInsertHooks = []BancoHook{}

	AddBancoHook(boil.AfterInsertHook, bancoAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	bancoAfterInsertHooks = []BancoHook{}

	AddBancoHook(boil.AfterSelectHook, bancoAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	bancoAfterSelectHooks = []BancoHook{}

	AddBancoHook(boil.BeforeUpdateHook, bancoBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	bancoBeforeUpdateHooks = []BancoHook{}

	AddBancoHook(boil.AfterUpdateHook, bancoAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	bancoAfterUpdateHooks = []BancoHook{}

	AddBancoHook(boil.BeforeDeleteHook, bancoBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	bancoBeforeDeleteHooks = []BancoHook{}

	AddBancoHook(boil.AfterDeleteHook, bancoAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	bancoAfterDeleteHooks = []BancoHook{}

	AddBancoHook(boil.BeforeUpsertHook, bancoBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	bancoBeforeUpsertHooks = []BancoHook{}

	AddBancoHook(boil.AfterUpsertHook, bancoAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	bancoAfterUpsertHooks = []BancoHook{}
}

func testBancosInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBancosInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(bancoColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBancoToManyBanBancoCarteiras(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c BancoCarteiras

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bancoCarteirasDBTypes, false, bancoCarteirasColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bancoCarteirasDBTypes, false, bancoCarteirasColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanBancoCarteiras().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanBancoCarteiras(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoCarteiras); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanBancoCarteiras = nil
	if err = a.L.LoadBanBancoCarteiras(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoCarteiras); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyBanBancoRemessaInstrucaos(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c BancoRemessaInstrucao

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bancoRemessaInstrucaoDBTypes, false, bancoRemessaInstrucaoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bancoRemessaInstrucaoDBTypes, false, bancoRemessaInstrucaoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanBancoRemessaInstrucaos().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanBancoRemessaInstrucaos(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRemessaInstrucaos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanBancoRemessaInstrucaos = nil
	if err = a.L.LoadBanBancoRemessaInstrucaos(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRemessaInstrucaos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyBanBancoRemessaOcorrencia(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c BancoRemessaOcorrencium

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bancoRemessaOcorrenciumDBTypes, false, bancoRemessaOcorrenciumColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bancoRemessaOcorrenciumDBTypes, false, bancoRemessaOcorrenciumColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanBancoRemessaOcorrencia().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanBancoRemessaOcorrencia(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRemessaOcorrencia); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanBancoRemessaOcorrencia = nil
	if err = a.L.LoadBanBancoRemessaOcorrencia(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRemessaOcorrencia); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyBanBancoRetornoOcorrencia(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c BancoRetornoOcorrencium

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bancoRetornoOcorrenciumDBTypes, false, bancoRetornoOcorrenciumColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bancoRetornoOcorrenciumDBTypes, false, bancoRetornoOcorrenciumColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanBancoRetornoOcorrencia().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanBancoRetornoOcorrencia(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRetornoOcorrencia); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanBancoRetornoOcorrencia = nil
	if err = a.L.LoadBanBancoRetornoOcorrencia(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRetornoOcorrencia); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyBanBancoRetornoRejeicaos(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c BancoRetornoRejeicao

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bancoRetornoRejeicaoDBTypes, false, bancoRetornoRejeicaoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bancoRetornoRejeicaoDBTypes, false, bancoRetornoRejeicaoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanBancoRetornoRejeicaos().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanBancoRetornoRejeicaos(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRetornoRejeicaos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanBancoRetornoRejeicaos = nil
	if err = a.L.LoadBanBancoRetornoRejeicaos(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoRetornoRejeicaos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyBanBancoTipoDocumentos(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c BancoTipoDocumento

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bancoTipoDocumentoDBTypes, false, bancoTipoDocumentoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bancoTipoDocumentoDBTypes, false, bancoTipoDocumentoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanBancoTipoDocumentos().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanBancoTipoDocumentos(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoTipoDocumentos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanBancoTipoDocumentos = nil
	if err = a.L.LoadBanBancoTipoDocumentos(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanBancoTipoDocumentos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyBanChequesRecebidos(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c ChequesRecebido

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, chequesRecebidoDBTypes, false, chequesRecebidoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, chequesRecebidoDBTypes, false, chequesRecebidoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanChequesRecebidos().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanChequesRecebidos(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanChequesRecebidos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanChequesRecebidos = nil
	if err = a.L.LoadBanChequesRecebidos(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanChequesRecebidos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyBanContaBancaria(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c ContaBancarium

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, contaBancariumDBTypes, false, contaBancariumColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, contaBancariumDBTypes, false, contaBancariumColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BanID = a.BanID
	c.BanID = a.BanID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BanContaBancaria().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BanID == b.BanID {
			bFound = true
		}
		if v.BanID == c.BanID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BancoSlice{&a}
	if err = a.L.LoadBanContaBancaria(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanContaBancaria); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BanContaBancaria = nil
	if err = a.L.LoadBanContaBancaria(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BanContaBancaria); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBancoToManyAddOpBanBancoCarteiras(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e BancoCarteiras

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BancoCarteiras{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bancoCarteirasDBTypes, false, strmangle.SetComplement(bancoCarteirasPrimaryKeyColumns, bancoCarteirasColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BancoCarteiras{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanBancoCarteiras(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanBancoCarteiras[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanBancoCarteiras[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanBancoCarteiras().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToManyAddOpBanBancoRemessaInstrucaos(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e BancoRemessaInstrucao

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BancoRemessaInstrucao{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bancoRemessaInstrucaoDBTypes, false, strmangle.SetComplement(bancoRemessaInstrucaoPrimaryKeyColumns, bancoRemessaInstrucaoColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BancoRemessaInstrucao{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanBancoRemessaInstrucaos(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanBancoRemessaInstrucaos[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanBancoRemessaInstrucaos[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanBancoRemessaInstrucaos().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToManyAddOpBanBancoRemessaOcorrencia(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e BancoRemessaOcorrencium

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BancoRemessaOcorrencium{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bancoRemessaOcorrenciumDBTypes, false, strmangle.SetComplement(bancoRemessaOcorrenciumPrimaryKeyColumns, bancoRemessaOcorrenciumColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BancoRemessaOcorrencium{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanBancoRemessaOcorrencia(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanBancoRemessaOcorrencia[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanBancoRemessaOcorrencia[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanBancoRemessaOcorrencia().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToManyAddOpBanBancoRetornoOcorrencia(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e BancoRetornoOcorrencium

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BancoRetornoOcorrencium{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bancoRetornoOcorrenciumDBTypes, false, strmangle.SetComplement(bancoRetornoOcorrenciumPrimaryKeyColumns, bancoRetornoOcorrenciumColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BancoRetornoOcorrencium{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanBancoRetornoOcorrencia(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanBancoRetornoOcorrencia[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanBancoRetornoOcorrencia[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanBancoRetornoOcorrencia().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToManyAddOpBanBancoRetornoRejeicaos(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e BancoRetornoRejeicao

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BancoRetornoRejeicao{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bancoRetornoRejeicaoDBTypes, false, strmangle.SetComplement(bancoRetornoRejeicaoPrimaryKeyColumns, bancoRetornoRejeicaoColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BancoRetornoRejeicao{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanBancoRetornoRejeicaos(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanBancoRetornoRejeicaos[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanBancoRetornoRejeicaos[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanBancoRetornoRejeicaos().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToManyAddOpBanBancoTipoDocumentos(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e BancoTipoDocumento

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BancoTipoDocumento{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bancoTipoDocumentoDBTypes, false, strmangle.SetComplement(bancoTipoDocumentoPrimaryKeyColumns, bancoTipoDocumentoColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BancoTipoDocumento{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanBancoTipoDocumentos(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanBancoTipoDocumentos[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanBancoTipoDocumentos[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanBancoTipoDocumentos().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToManyAddOpBanChequesRecebidos(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e ChequesRecebido

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ChequesRecebido{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, chequesRecebidoDBTypes, false, strmangle.SetComplement(chequesRecebidoPrimaryKeyColumns, chequesRecebidoColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*ChequesRecebido{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanChequesRecebidos(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanChequesRecebidos[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanChequesRecebidos[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanChequesRecebidos().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToManyAddOpBanContaBancaria(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c, d, e ContaBancarium

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ContaBancarium{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, contaBancariumDBTypes, false, strmangle.SetComplement(contaBancariumPrimaryKeyColumns, contaBancariumColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*ContaBancarium{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBanContaBancaria(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.BanID != first.BanID {
			t.Error("foreign key was wrong value", a.BanID, first.BanID)
		}
		if a.BanID != second.BanID {
			t.Error("foreign key was wrong value", a.BanID, second.BanID)
		}

		if first.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Ban != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BanContaBancaria[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BanContaBancaria[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BanContaBancaria().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBancoToOneEmpresaFilialUsingEmf(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Banco
	var foreign EmpresaFilial

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, bancoDBTypes, false, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, empresaFilialDBTypes, false, empresaFilialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EmpresaFilial struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.EmfID = foreign.EmfID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Emf().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.EmfID != foreign.EmfID {
		t.Errorf("want: %v, got %v", foreign.EmfID, check.EmfID)
	}

	ranAfterSelectHook := false
	AddEmpresaFilialHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *EmpresaFilial) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := BancoSlice{&local}
	if err = local.L.LoadEmf(ctx, tx, false, (*[]*Banco)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Emf == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Emf = nil
	if err = local.L.LoadEmf(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Emf == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testBancoToOneSetOpEmpresaFilialUsingEmf(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Banco
	var b, c EmpresaFilial

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bancoDBTypes, false, strmangle.SetComplement(bancoPrimaryKeyColumns, bancoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, empresaFilialDBTypes, false, strmangle.SetComplement(empresaFilialPrimaryKeyColumns, empresaFilialColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, empresaFilialDBTypes, false, strmangle.SetComplement(empresaFilialPrimaryKeyColumns, empresaFilialColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*EmpresaFilial{&b, &c} {
		err = a.SetEmf(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Emf != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.EmfBancos[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.EmfID != x.EmfID {
			t.Error("foreign key was wrong value", a.EmfID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.EmfID))
		reflect.Indirect(reflect.ValueOf(&a.EmfID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.EmfID != x.EmfID {
			t.Error("foreign key was wrong value", a.EmfID, x.EmfID)
		}
	}
}

func testBancosReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBancosReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BancoSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBancosSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Bancos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	bancoDBTypes = map[string]string{`BanID`: `int`, `EmfID`: `int`, `BanCodigo`: `int`, `BanDescricao`: `varchar`, `BanPastaremessa`: `varchar`, `BanPastaretorno`: `varchar`, `BanSituacao`: `int`}
	_            = bytes.MinRead
)

func testBancosUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(bancoPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(bancoAllColumns) == len(bancoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBancosSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(bancoAllColumns) == len(bancoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Banco{}
	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bancoDBTypes, true, bancoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(bancoAllColumns, bancoPrimaryKeyColumns) {
		fields = bancoAllColumns
	} else {
		fields = strmangle.SetComplement(
			bancoAllColumns,
			bancoPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BancoSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBancosUpsert(t *testing.T) {
	t.Parallel()

	if len(bancoAllColumns) == len(bancoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLBancoUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Banco{}
	if err = randomize.Struct(seed, &o, bancoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Banco: %s", err)
	}

	count, err := Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, bancoDBTypes, false, bancoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Banco struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Banco: %s", err)
	}

	count, err = Bancos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
