// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCests(t *testing.T) {
	t.Parallel()

	query := Cests()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCestsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCestsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Cests().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCestsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CestSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCestsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CestExists(ctx, tx, o.CestNumero)
	if err != nil {
		t.Errorf("Unable to check if Cest exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CestExists to return true, but got false.")
	}
}

func testCestsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	cestFound, err := FindCest(ctx, tx, o.CestNumero)
	if err != nil {
		t.Error(err)
	}

	if cestFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCestsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Cests().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCestsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Cests().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCestsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cestOne := &Cest{}
	cestTwo := &Cest{}
	if err = randomize.Struct(seed, cestOne, cestDBTypes, false, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}
	if err = randomize.Struct(seed, cestTwo, cestDBTypes, false, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = cestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = cestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Cests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCestsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	cestOne := &Cest{}
	cestTwo := &Cest{}
	if err = randomize.Struct(seed, cestOne, cestDBTypes, false, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}
	if err = randomize.Struct(seed, cestTwo, cestDBTypes, false, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = cestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = cestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func cestBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func cestAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Cest) error {
	*o = Cest{}
	return nil
}

func testCestsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Cest{}
	o := &Cest{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, cestDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Cest object: %s", err)
	}

	AddCestHook(boil.BeforeInsertHook, cestBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	cestBeforeInsertHooks = []CestHook{}

	AddCestHook(boil.AfterInsertHook, cestAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	cestAfterInsertHooks = []CestHook{}

	AddCestHook(boil.AfterSelectHook, cestAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	cestAfterSelectHooks = []CestHook{}

	AddCestHook(boil.BeforeUpdateHook, cestBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	cestBeforeUpdateHooks = []CestHook{}

	AddCestHook(boil.AfterUpdateHook, cestAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	cestAfterUpdateHooks = []CestHook{}

	AddCestHook(boil.BeforeDeleteHook, cestBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	cestBeforeDeleteHooks = []CestHook{}

	AddCestHook(boil.AfterDeleteHook, cestAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	cestAfterDeleteHooks = []CestHook{}

	AddCestHook(boil.BeforeUpsertHook, cestBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	cestBeforeUpsertHooks = []CestHook{}

	AddCestHook(boil.AfterUpsertHook, cestAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	cestAfterUpsertHooks = []CestHook{}
}

func testCestsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCestsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(cestColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCestToManyCestNumeroNCMS(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Cest
	var b, c NCM

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, ncmDBTypes, false, ncmColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, ncmDBTypes, false, ncmColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.CestNumero, a.CestNumero)
	queries.Assign(&c.CestNumero, a.CestNumero)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.CestNumeroNCMS().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.CestNumero, b.CestNumero) {
			bFound = true
		}
		if queries.Equal(v.CestNumero, c.CestNumero) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := CestSlice{&a}
	if err = a.L.LoadCestNumeroNCMS(ctx, tx, false, (*[]*Cest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CestNumeroNCMS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.CestNumeroNCMS = nil
	if err = a.L.LoadCestNumeroNCMS(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CestNumeroNCMS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testCestToManyAddOpCestNumeroNCMS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Cest
	var b, c, d, e NCM

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cestDBTypes, false, strmangle.SetComplement(cestPrimaryKeyColumns, cestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*NCM{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, ncmDBTypes, false, strmangle.SetComplement(ncmPrimaryKeyColumns, ncmColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*NCM{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCestNumeroNCMS(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.CestNumero, first.CestNumero) {
			t.Error("foreign key was wrong value", a.CestNumero, first.CestNumero)
		}
		if !queries.Equal(a.CestNumero, second.CestNumero) {
			t.Error("foreign key was wrong value", a.CestNumero, second.CestNumero)
		}

		if first.R.CestNumeroCest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.CestNumeroCest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.CestNumeroNCMS[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.CestNumeroNCMS[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.CestNumeroNCMS().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testCestToManySetOpCestNumeroNCMS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Cest
	var b, c, d, e NCM

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cestDBTypes, false, strmangle.SetComplement(cestPrimaryKeyColumns, cestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*NCM{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, ncmDBTypes, false, strmangle.SetComplement(ncmPrimaryKeyColumns, ncmColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetCestNumeroNCMS(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.CestNumeroNCMS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetCestNumeroNCMS(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.CestNumeroNCMS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.CestNumero) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.CestNumero) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.CestNumero, d.CestNumero) {
		t.Error("foreign key was wrong value", a.CestNumero, d.CestNumero)
	}
	if !queries.Equal(a.CestNumero, e.CestNumero) {
		t.Error("foreign key was wrong value", a.CestNumero, e.CestNumero)
	}

	if b.R.CestNumeroCest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.CestNumeroCest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.CestNumeroCest != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.CestNumeroCest != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.CestNumeroNCMS[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.CestNumeroNCMS[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testCestToManyRemoveOpCestNumeroNCMS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Cest
	var b, c, d, e NCM

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cestDBTypes, false, strmangle.SetComplement(cestPrimaryKeyColumns, cestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*NCM{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, ncmDBTypes, false, strmangle.SetComplement(ncmPrimaryKeyColumns, ncmColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddCestNumeroNCMS(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.CestNumeroNCMS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveCestNumeroNCMS(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.CestNumeroNCMS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.CestNumero) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.CestNumero) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.CestNumeroCest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.CestNumeroCest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.CestNumeroCest != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.CestNumeroCest != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.CestNumeroNCMS) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.CestNumeroNCMS[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.CestNumeroNCMS[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testCestsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCestsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CestSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCestsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Cests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	cestDBTypes = map[string]string{`CestNumero`: `int`, `CestSegmento`: `varchar`, `CestDescricao`: `varchar`, `CestItem`: `varchar`, `CestAnexoXxvii`: `varchar`}
	_           = bytes.MinRead
)

func testCestsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(cestPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(cestAllColumns) == len(cestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, cestDBTypes, true, cestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCestsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(cestAllColumns) == len(cestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Cest{}
	if err = randomize.Struct(seed, o, cestDBTypes, true, cestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, cestDBTypes, true, cestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(cestAllColumns, cestPrimaryKeyColumns) {
		fields = cestAllColumns
	} else {
		fields = strmangle.SetComplement(
			cestAllColumns,
			cestPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CestSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCestsUpsert(t *testing.T) {
	t.Parallel()

	if len(cestAllColumns) == len(cestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLCestUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Cest{}
	if err = randomize.Struct(seed, &o, cestDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Cest: %s", err)
	}

	count, err := Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, cestDBTypes, false, cestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Cest struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Cest: %s", err)
	}

	count, err = Cests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
