// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testContratoEntidadeTipos(t *testing.T) {
	t.Parallel()

	query := ContratoEntidadeTipos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testContratoEntidadeTiposDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContratoEntidadeTiposQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ContratoEntidadeTipos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContratoEntidadeTiposSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ContratoEntidadeTipoSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContratoEntidadeTiposExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ContratoEntidadeTipoExists(ctx, tx, o.CetID)
	if err != nil {
		t.Errorf("Unable to check if ContratoEntidadeTipo exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ContratoEntidadeTipoExists to return true, but got false.")
	}
}

func testContratoEntidadeTiposFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	contratoEntidadeTipoFound, err := FindContratoEntidadeTipo(ctx, tx, o.CetID)
	if err != nil {
		t.Error(err)
	}

	if contratoEntidadeTipoFound == nil {
		t.Error("want a record, got nil")
	}
}

func testContratoEntidadeTiposBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ContratoEntidadeTipos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testContratoEntidadeTiposOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ContratoEntidadeTipos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testContratoEntidadeTiposAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	contratoEntidadeTipoOne := &ContratoEntidadeTipo{}
	contratoEntidadeTipoTwo := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, contratoEntidadeTipoOne, contratoEntidadeTipoDBTypes, false, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}
	if err = randomize.Struct(seed, contratoEntidadeTipoTwo, contratoEntidadeTipoDBTypes, false, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = contratoEntidadeTipoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = contratoEntidadeTipoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ContratoEntidadeTipos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testContratoEntidadeTiposCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	contratoEntidadeTipoOne := &ContratoEntidadeTipo{}
	contratoEntidadeTipoTwo := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, contratoEntidadeTipoOne, contratoEntidadeTipoDBTypes, false, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}
	if err = randomize.Struct(seed, contratoEntidadeTipoTwo, contratoEntidadeTipoDBTypes, false, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = contratoEntidadeTipoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = contratoEntidadeTipoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func contratoEntidadeTipoBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func contratoEntidadeTipoAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ContratoEntidadeTipo) error {
	*o = ContratoEntidadeTipo{}
	return nil
}

func testContratoEntidadeTiposHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ContratoEntidadeTipo{}
	o := &ContratoEntidadeTipo{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo object: %s", err)
	}

	AddContratoEntidadeTipoHook(boil.BeforeInsertHook, contratoEntidadeTipoBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoBeforeInsertHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.AfterInsertHook, contratoEntidadeTipoAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoAfterInsertHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.AfterSelectHook, contratoEntidadeTipoAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoAfterSelectHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.BeforeUpdateHook, contratoEntidadeTipoBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoBeforeUpdateHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.AfterUpdateHook, contratoEntidadeTipoAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoAfterUpdateHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.BeforeDeleteHook, contratoEntidadeTipoBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoBeforeDeleteHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.AfterDeleteHook, contratoEntidadeTipoAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoAfterDeleteHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.BeforeUpsertHook, contratoEntidadeTipoBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoBeforeUpsertHooks = []ContratoEntidadeTipoHook{}

	AddContratoEntidadeTipoHook(boil.AfterUpsertHook, contratoEntidadeTipoAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	contratoEntidadeTipoAfterUpsertHooks = []ContratoEntidadeTipoHook{}
}

func testContratoEntidadeTiposInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testContratoEntidadeTiposInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(contratoEntidadeTipoColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testContratoEntidadeTipoToManyCetContratoEntidades(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ContratoEntidadeTipo
	var b, c ContratoEntidade

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, contratoEntidadeDBTypes, false, contratoEntidadeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, contratoEntidadeDBTypes, false, contratoEntidadeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.CetID = a.CetID
	c.CetID = a.CetID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.CetContratoEntidades().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.CetID == b.CetID {
			bFound = true
		}
		if v.CetID == c.CetID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ContratoEntidadeTipoSlice{&a}
	if err = a.L.LoadCetContratoEntidades(ctx, tx, false, (*[]*ContratoEntidadeTipo)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CetContratoEntidades); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.CetContratoEntidades = nil
	if err = a.L.LoadCetContratoEntidades(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CetContratoEntidades); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testContratoEntidadeTipoToManyAddOpCetContratoEntidades(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ContratoEntidadeTipo
	var b, c, d, e ContratoEntidade

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contratoEntidadeTipoDBTypes, false, strmangle.SetComplement(contratoEntidadeTipoPrimaryKeyColumns, contratoEntidadeTipoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ContratoEntidade{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, contratoEntidadeDBTypes, false, strmangle.SetComplement(contratoEntidadePrimaryKeyColumns, contratoEntidadeColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*ContratoEntidade{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCetContratoEntidades(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.CetID != first.CetID {
			t.Error("foreign key was wrong value", a.CetID, first.CetID)
		}
		if a.CetID != second.CetID {
			t.Error("foreign key was wrong value", a.CetID, second.CetID)
		}

		if first.R.Cet != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Cet != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.CetContratoEntidades[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.CetContratoEntidades[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.CetContratoEntidades().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testContratoEntidadeTipoToOneDespesasUsingDesp(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ContratoEntidadeTipo
	var foreign Despesas

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, despesasDBTypes, false, despesasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Despesas struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.DespID, foreign.DespID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Desp().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.DespID, foreign.DespID) {
		t.Errorf("want: %v, got %v", foreign.DespID, check.DespID)
	}

	ranAfterSelectHook := false
	AddDespesasHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Despesas) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ContratoEntidadeTipoSlice{&local}
	if err = local.L.LoadDesp(ctx, tx, false, (*[]*ContratoEntidadeTipo)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Desp == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Desp = nil
	if err = local.L.LoadDesp(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Desp == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testContratoEntidadeTipoToOneReceitasUsingRec(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ContratoEntidadeTipo
	var foreign Receitas

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, receitasDBTypes, false, receitasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Receitas struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.RecID, foreign.RecID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Rec().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.RecID, foreign.RecID) {
		t.Errorf("want: %v, got %v", foreign.RecID, check.RecID)
	}

	ranAfterSelectHook := false
	AddReceitasHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Receitas) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ContratoEntidadeTipoSlice{&local}
	if err = local.L.LoadRec(ctx, tx, false, (*[]*ContratoEntidadeTipo)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Rec == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Rec = nil
	if err = local.L.LoadRec(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Rec == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testContratoEntidadeTipoToOneSetOpDespesasUsingDesp(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ContratoEntidadeTipo
	var b, c Despesas

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contratoEntidadeTipoDBTypes, false, strmangle.SetComplement(contratoEntidadeTipoPrimaryKeyColumns, contratoEntidadeTipoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, despesasDBTypes, false, strmangle.SetComplement(despesasPrimaryKeyColumns, despesasColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, despesasDBTypes, false, strmangle.SetComplement(despesasPrimaryKeyColumns, despesasColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Despesas{&b, &c} {
		err = a.SetDesp(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Desp != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DespContratoEntidadeTipos[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.DespID, x.DespID) {
			t.Error("foreign key was wrong value", a.DespID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DespID))
		reflect.Indirect(reflect.ValueOf(&a.DespID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.DespID, x.DespID) {
			t.Error("foreign key was wrong value", a.DespID, x.DespID)
		}
	}
}

func testContratoEntidadeTipoToOneRemoveOpDespesasUsingDesp(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ContratoEntidadeTipo
	var b Despesas

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contratoEntidadeTipoDBTypes, false, strmangle.SetComplement(contratoEntidadeTipoPrimaryKeyColumns, contratoEntidadeTipoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, despesasDBTypes, false, strmangle.SetComplement(despesasPrimaryKeyColumns, despesasColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetDesp(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveDesp(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Desp().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Desp != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.DespID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.DespContratoEntidadeTipos) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testContratoEntidadeTipoToOneSetOpReceitasUsingRec(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ContratoEntidadeTipo
	var b, c Receitas

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contratoEntidadeTipoDBTypes, false, strmangle.SetComplement(contratoEntidadeTipoPrimaryKeyColumns, contratoEntidadeTipoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, receitasDBTypes, false, strmangle.SetComplement(receitasPrimaryKeyColumns, receitasColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, receitasDBTypes, false, strmangle.SetComplement(receitasPrimaryKeyColumns, receitasColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Receitas{&b, &c} {
		err = a.SetRec(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Rec != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RecContratoEntidadeTipos[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.RecID, x.RecID) {
			t.Error("foreign key was wrong value", a.RecID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.RecID))
		reflect.Indirect(reflect.ValueOf(&a.RecID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.RecID, x.RecID) {
			t.Error("foreign key was wrong value", a.RecID, x.RecID)
		}
	}
}

func testContratoEntidadeTipoToOneRemoveOpReceitasUsingRec(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ContratoEntidadeTipo
	var b Receitas

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contratoEntidadeTipoDBTypes, false, strmangle.SetComplement(contratoEntidadeTipoPrimaryKeyColumns, contratoEntidadeTipoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, receitasDBTypes, false, strmangle.SetComplement(receitasPrimaryKeyColumns, receitasColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetRec(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveRec(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Rec().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Rec != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.RecID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.RecContratoEntidadeTipos) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testContratoEntidadeTiposReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testContratoEntidadeTiposReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ContratoEntidadeTipoSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testContratoEntidadeTiposSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ContratoEntidadeTipos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	contratoEntidadeTipoDBTypes = map[string]string{`CetID`: `int`, `CetNome`: `varchar`, `RecID`: `int`, `DespID`: `int`}
	_                           = bytes.MinRead
)

func testContratoEntidadeTiposUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(contratoEntidadeTipoPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(contratoEntidadeTipoAllColumns) == len(contratoEntidadeTipoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testContratoEntidadeTiposSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(contratoEntidadeTipoAllColumns) == len(contratoEntidadeTipoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, contratoEntidadeTipoDBTypes, true, contratoEntidadeTipoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(contratoEntidadeTipoAllColumns, contratoEntidadeTipoPrimaryKeyColumns) {
		fields = contratoEntidadeTipoAllColumns
	} else {
		fields = strmangle.SetComplement(
			contratoEntidadeTipoAllColumns,
			contratoEntidadeTipoPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ContratoEntidadeTipoSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testContratoEntidadeTiposUpsert(t *testing.T) {
	t.Parallel()

	if len(contratoEntidadeTipoAllColumns) == len(contratoEntidadeTipoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLContratoEntidadeTipoUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ContratoEntidadeTipo{}
	if err = randomize.Struct(seed, &o, contratoEntidadeTipoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ContratoEntidadeTipo: %s", err)
	}

	count, err := ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, contratoEntidadeTipoDBTypes, false, contratoEntidadeTipoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ContratoEntidadeTipo struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ContratoEntidadeTipo: %s", err)
	}

	count, err = ContratoEntidadeTipos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
