// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCorDenatrans(t *testing.T) {
	t.Parallel()

	query := CorDenatrans()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCorDenatransDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCorDenatransQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CorDenatrans().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCorDenatransSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CorDenatranSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCorDenatransExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CorDenatranExists(ctx, tx, o.CordCodigo)
	if err != nil {
		t.Errorf("Unable to check if CorDenatran exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CorDenatranExists to return true, but got false.")
	}
}

func testCorDenatransFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	corDenatranFound, err := FindCorDenatran(ctx, tx, o.CordCodigo)
	if err != nil {
		t.Error(err)
	}

	if corDenatranFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCorDenatransBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CorDenatrans().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCorDenatransOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CorDenatrans().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCorDenatransAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	corDenatranOne := &CorDenatran{}
	corDenatranTwo := &CorDenatran{}
	if err = randomize.Struct(seed, corDenatranOne, corDenatranDBTypes, false, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}
	if err = randomize.Struct(seed, corDenatranTwo, corDenatranDBTypes, false, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = corDenatranOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = corDenatranTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CorDenatrans().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCorDenatransCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	corDenatranOne := &CorDenatran{}
	corDenatranTwo := &CorDenatran{}
	if err = randomize.Struct(seed, corDenatranOne, corDenatranDBTypes, false, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}
	if err = randomize.Struct(seed, corDenatranTwo, corDenatranDBTypes, false, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = corDenatranOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = corDenatranTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func corDenatranBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func corDenatranAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CorDenatran) error {
	*o = CorDenatran{}
	return nil
}

func testCorDenatransHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &CorDenatran{}
	o := &CorDenatran{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, corDenatranDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CorDenatran object: %s", err)
	}

	AddCorDenatranHook(boil.BeforeInsertHook, corDenatranBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	corDenatranBeforeInsertHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.AfterInsertHook, corDenatranAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	corDenatranAfterInsertHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.AfterSelectHook, corDenatranAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	corDenatranAfterSelectHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.BeforeUpdateHook, corDenatranBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	corDenatranBeforeUpdateHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.AfterUpdateHook, corDenatranAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	corDenatranAfterUpdateHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.BeforeDeleteHook, corDenatranBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	corDenatranBeforeDeleteHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.AfterDeleteHook, corDenatranAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	corDenatranAfterDeleteHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.BeforeUpsertHook, corDenatranBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	corDenatranBeforeUpsertHooks = []CorDenatranHook{}

	AddCorDenatranHook(boil.AfterUpsertHook, corDenatranAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	corDenatranAfterUpsertHooks = []CorDenatranHook{}
}

func testCorDenatransInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCorDenatransInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(corDenatranColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCorDenatranToManyCordCodigoNotaFiscalItemVeiculos(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CorDenatran
	var b, c NotaFiscalItemVeiculo

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, notaFiscalItemVeiculoDBTypes, false, notaFiscalItemVeiculoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, notaFiscalItemVeiculoDBTypes, false, notaFiscalItemVeiculoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.CordCodigo = a.CordCodigo
	c.CordCodigo = a.CordCodigo

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.CordCodigoNotaFiscalItemVeiculos().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.CordCodigo == b.CordCodigo {
			bFound = true
		}
		if v.CordCodigo == c.CordCodigo {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := CorDenatranSlice{&a}
	if err = a.L.LoadCordCodigoNotaFiscalItemVeiculos(ctx, tx, false, (*[]*CorDenatran)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CordCodigoNotaFiscalItemVeiculos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.CordCodigoNotaFiscalItemVeiculos = nil
	if err = a.L.LoadCordCodigoNotaFiscalItemVeiculos(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CordCodigoNotaFiscalItemVeiculos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testCorDenatranToManyAddOpCordCodigoNotaFiscalItemVeiculos(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CorDenatran
	var b, c, d, e NotaFiscalItemVeiculo

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, corDenatranDBTypes, false, strmangle.SetComplement(corDenatranPrimaryKeyColumns, corDenatranColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*NotaFiscalItemVeiculo{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, notaFiscalItemVeiculoDBTypes, false, strmangle.SetComplement(notaFiscalItemVeiculoPrimaryKeyColumns, notaFiscalItemVeiculoColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*NotaFiscalItemVeiculo{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCordCodigoNotaFiscalItemVeiculos(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.CordCodigo != first.CordCodigo {
			t.Error("foreign key was wrong value", a.CordCodigo, first.CordCodigo)
		}
		if a.CordCodigo != second.CordCodigo {
			t.Error("foreign key was wrong value", a.CordCodigo, second.CordCodigo)
		}

		if first.R.CordCodigoCorDenatran != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.CordCodigoCorDenatran != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.CordCodigoNotaFiscalItemVeiculos[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.CordCodigoNotaFiscalItemVeiculos[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.CordCodigoNotaFiscalItemVeiculos().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testCorDenatransReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCorDenatransReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CorDenatranSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCorDenatransSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CorDenatrans().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	corDenatranDBTypes = map[string]string{`CordCodigo`: `varchar`, `CordDescricao`: `varchar`}
	_                  = bytes.MinRead
)

func testCorDenatransUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(corDenatranPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(corDenatranAllColumns) == len(corDenatranPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCorDenatransSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(corDenatranAllColumns) == len(corDenatranPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CorDenatran{}
	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, corDenatranDBTypes, true, corDenatranPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(corDenatranAllColumns, corDenatranPrimaryKeyColumns) {
		fields = corDenatranAllColumns
	} else {
		fields = strmangle.SetComplement(
			corDenatranAllColumns,
			corDenatranPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CorDenatranSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCorDenatransUpsert(t *testing.T) {
	t.Parallel()

	if len(corDenatranAllColumns) == len(corDenatranPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLCorDenatranUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CorDenatran{}
	if err = randomize.Struct(seed, &o, corDenatranDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CorDenatran: %s", err)
	}

	count, err := CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, corDenatranDBTypes, false, corDenatranPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CorDenatran struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CorDenatran: %s", err)
	}

	count, err = CorDenatrans().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
