// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EventoOperacao is an object representing the database table.
type EventoOperacao struct {
	EveNumero    int   `boil:"eve_numero" json:"eve_numero" toml:"eve_numero" yaml:"eve_numero"`
	EvoItem      int16 `boil:"evo_item" json:"evo_item" toml:"evo_item" yaml:"evo_item"`
	EvoEveNumero int   `boil:"evo_eve_numero" json:"evo_eve_numero" toml:"evo_eve_numero" yaml:"evo_eve_numero"`
	EvoOperador  int16 `boil:"evo_operador" json:"evo_operador" toml:"evo_operador" yaml:"evo_operador"`

	R *eventoOperacaoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventoOperacaoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EventoOperacaoColumns = struct {
	EveNumero    string
	EvoItem      string
	EvoEveNumero string
	EvoOperador  string
}{
	EveNumero:    "eve_numero",
	EvoItem:      "evo_item",
	EvoEveNumero: "evo_eve_numero",
	EvoOperador:  "evo_operador",
}

var EventoOperacaoTableColumns = struct {
	EveNumero    string
	EvoItem      string
	EvoEveNumero string
	EvoOperador  string
}{
	EveNumero:    "evento_operacao.eve_numero",
	EvoItem:      "evento_operacao.evo_item",
	EvoEveNumero: "evento_operacao.evo_eve_numero",
	EvoOperador:  "evento_operacao.evo_operador",
}

// Generated where

var EventoOperacaoWhere = struct {
	EveNumero    whereHelperint
	EvoItem      whereHelperint16
	EvoEveNumero whereHelperint
	EvoOperador  whereHelperint16
}{
	EveNumero:    whereHelperint{field: "`evento_operacao`.`eve_numero`"},
	EvoItem:      whereHelperint16{field: "`evento_operacao`.`evo_item`"},
	EvoEveNumero: whereHelperint{field: "`evento_operacao`.`evo_eve_numero`"},
	EvoOperador:  whereHelperint16{field: "`evento_operacao`.`evo_operador`"},
}

// EventoOperacaoRels is where relationship names are stored.
var EventoOperacaoRels = struct {
	EvoEveNumeroEvento string
	EveNumeroEvento    string
}{
	EvoEveNumeroEvento: "EvoEveNumeroEvento",
	EveNumeroEvento:    "EveNumeroEvento",
}

// eventoOperacaoR is where relationships are stored.
type eventoOperacaoR struct {
	EvoEveNumeroEvento *Evento `boil:"EvoEveNumeroEvento" json:"EvoEveNumeroEvento" toml:"EvoEveNumeroEvento" yaml:"EvoEveNumeroEvento"`
	EveNumeroEvento    *Evento `boil:"EveNumeroEvento" json:"EveNumeroEvento" toml:"EveNumeroEvento" yaml:"EveNumeroEvento"`
}

// NewStruct creates a new relationship struct
func (*eventoOperacaoR) NewStruct() *eventoOperacaoR {
	return &eventoOperacaoR{}
}

func (r *eventoOperacaoR) GetEvoEveNumeroEvento() *Evento {
	if r == nil {
		return nil
	}
	return r.EvoEveNumeroEvento
}

func (r *eventoOperacaoR) GetEveNumeroEvento() *Evento {
	if r == nil {
		return nil
	}
	return r.EveNumeroEvento
}

// eventoOperacaoL is where Load methods for each relationship are stored.
type eventoOperacaoL struct{}

var (
	eventoOperacaoAllColumns            = []string{"eve_numero", "evo_item", "evo_eve_numero", "evo_operador"}
	eventoOperacaoColumnsWithoutDefault = []string{"eve_numero", "evo_item", "evo_eve_numero", "evo_operador"}
	eventoOperacaoColumnsWithDefault    = []string{}
	eventoOperacaoPrimaryKeyColumns     = []string{"eve_numero", "evo_item"}
	eventoOperacaoGeneratedColumns      = []string{}
)

type (
	// EventoOperacaoSlice is an alias for a slice of pointers to EventoOperacao.
	// This should almost always be used instead of []EventoOperacao.
	EventoOperacaoSlice []*EventoOperacao
	// EventoOperacaoHook is the signature for custom EventoOperacao hook methods
	EventoOperacaoHook func(context.Context, boil.ContextExecutor, *EventoOperacao) error

	eventoOperacaoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	eventoOperacaoType                 = reflect.TypeOf(&EventoOperacao{})
	eventoOperacaoMapping              = queries.MakeStructMapping(eventoOperacaoType)
	eventoOperacaoPrimaryKeyMapping, _ = queries.BindMapping(eventoOperacaoType, eventoOperacaoMapping, eventoOperacaoPrimaryKeyColumns)
	eventoOperacaoInsertCacheMut       sync.RWMutex
	eventoOperacaoInsertCache          = make(map[string]insertCache)
	eventoOperacaoUpdateCacheMut       sync.RWMutex
	eventoOperacaoUpdateCache          = make(map[string]updateCache)
	eventoOperacaoUpsertCacheMut       sync.RWMutex
	eventoOperacaoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var eventoOperacaoAfterSelectMu sync.Mutex
var eventoOperacaoAfterSelectHooks []EventoOperacaoHook

var eventoOperacaoBeforeInsertMu sync.Mutex
var eventoOperacaoBeforeInsertHooks []EventoOperacaoHook
var eventoOperacaoAfterInsertMu sync.Mutex
var eventoOperacaoAfterInsertHooks []EventoOperacaoHook

var eventoOperacaoBeforeUpdateMu sync.Mutex
var eventoOperacaoBeforeUpdateHooks []EventoOperacaoHook
var eventoOperacaoAfterUpdateMu sync.Mutex
var eventoOperacaoAfterUpdateHooks []EventoOperacaoHook

var eventoOperacaoBeforeDeleteMu sync.Mutex
var eventoOperacaoBeforeDeleteHooks []EventoOperacaoHook
var eventoOperacaoAfterDeleteMu sync.Mutex
var eventoOperacaoAfterDeleteHooks []EventoOperacaoHook

var eventoOperacaoBeforeUpsertMu sync.Mutex
var eventoOperacaoBeforeUpsertHooks []EventoOperacaoHook
var eventoOperacaoAfterUpsertMu sync.Mutex
var eventoOperacaoAfterUpsertHooks []EventoOperacaoHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EventoOperacao) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EventoOperacao) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EventoOperacao) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EventoOperacao) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EventoOperacao) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EventoOperacao) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EventoOperacao) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EventoOperacao) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EventoOperacao) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventoOperacaoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEventoOperacaoHook registers your hook function for all future operations.
func AddEventoOperacaoHook(hookPoint boil.HookPoint, eventoOperacaoHook EventoOperacaoHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		eventoOperacaoAfterSelectMu.Lock()
		eventoOperacaoAfterSelectHooks = append(eventoOperacaoAfterSelectHooks, eventoOperacaoHook)
		eventoOperacaoAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		eventoOperacaoBeforeInsertMu.Lock()
		eventoOperacaoBeforeInsertHooks = append(eventoOperacaoBeforeInsertHooks, eventoOperacaoHook)
		eventoOperacaoBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		eventoOperacaoAfterInsertMu.Lock()
		eventoOperacaoAfterInsertHooks = append(eventoOperacaoAfterInsertHooks, eventoOperacaoHook)
		eventoOperacaoAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		eventoOperacaoBeforeUpdateMu.Lock()
		eventoOperacaoBeforeUpdateHooks = append(eventoOperacaoBeforeUpdateHooks, eventoOperacaoHook)
		eventoOperacaoBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		eventoOperacaoAfterUpdateMu.Lock()
		eventoOperacaoAfterUpdateHooks = append(eventoOperacaoAfterUpdateHooks, eventoOperacaoHook)
		eventoOperacaoAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		eventoOperacaoBeforeDeleteMu.Lock()
		eventoOperacaoBeforeDeleteHooks = append(eventoOperacaoBeforeDeleteHooks, eventoOperacaoHook)
		eventoOperacaoBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		eventoOperacaoAfterDeleteMu.Lock()
		eventoOperacaoAfterDeleteHooks = append(eventoOperacaoAfterDeleteHooks, eventoOperacaoHook)
		eventoOperacaoAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		eventoOperacaoBeforeUpsertMu.Lock()
		eventoOperacaoBeforeUpsertHooks = append(eventoOperacaoBeforeUpsertHooks, eventoOperacaoHook)
		eventoOperacaoBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		eventoOperacaoAfterUpsertMu.Lock()
		eventoOperacaoAfterUpsertHooks = append(eventoOperacaoAfterUpsertHooks, eventoOperacaoHook)
		eventoOperacaoAfterUpsertMu.Unlock()
	}
}

// One returns a single eventoOperacao record from the query.
func (q eventoOperacaoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EventoOperacao, error) {
	o := &EventoOperacao{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for evento_operacao")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EventoOperacao records from the query.
func (q eventoOperacaoQuery) All(ctx context.Context, exec boil.ContextExecutor) (EventoOperacaoSlice, error) {
	var o []*EventoOperacao

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EventoOperacao slice")
	}

	if len(eventoOperacaoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EventoOperacao records in the query.
func (q eventoOperacaoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count evento_operacao rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q eventoOperacaoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if evento_operacao exists")
	}

	return count > 0, nil
}

// EvoEveNumeroEvento pointed to by the foreign key.
func (o *EventoOperacao) EvoEveNumeroEvento(mods ...qm.QueryMod) eventoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`eve_numero` = ?", o.EvoEveNumero),
	}

	queryMods = append(queryMods, mods...)

	return Eventos(queryMods...)
}

// EveNumeroEvento pointed to by the foreign key.
func (o *EventoOperacao) EveNumeroEvento(mods ...qm.QueryMod) eventoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`eve_numero` = ?", o.EveNumero),
	}

	queryMods = append(queryMods, mods...)

	return Eventos(queryMods...)
}

// LoadEvoEveNumeroEvento allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (eventoOperacaoL) LoadEvoEveNumeroEvento(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEventoOperacao interface{}, mods queries.Applicator) error {
	var slice []*EventoOperacao
	var object *EventoOperacao

	if singular {
		var ok bool
		object, ok = maybeEventoOperacao.(*EventoOperacao)
		if !ok {
			object = new(EventoOperacao)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEventoOperacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEventoOperacao))
			}
		}
	} else {
		s, ok := maybeEventoOperacao.(*[]*EventoOperacao)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEventoOperacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEventoOperacao))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &eventoOperacaoR{}
		}
		args[object.EvoEveNumero] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventoOperacaoR{}
			}

			args[obj.EvoEveNumero] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`evento`),
		qm.WhereIn(`evento.eve_numero in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Evento")
	}

	var resultSlice []*Evento
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Evento")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for evento")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for evento")
	}

	if len(eventoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EvoEveNumeroEvento = foreign
		if foreign.R == nil {
			foreign.R = &eventoR{}
		}
		foreign.R.EvoEveNumeroEventoOperacaos = append(foreign.R.EvoEveNumeroEventoOperacaos, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EvoEveNumero == foreign.EveNumero {
				local.R.EvoEveNumeroEvento = foreign
				if foreign.R == nil {
					foreign.R = &eventoR{}
				}
				foreign.R.EvoEveNumeroEventoOperacaos = append(foreign.R.EvoEveNumeroEventoOperacaos, local)
				break
			}
		}
	}

	return nil
}

// LoadEveNumeroEvento allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (eventoOperacaoL) LoadEveNumeroEvento(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEventoOperacao interface{}, mods queries.Applicator) error {
	var slice []*EventoOperacao
	var object *EventoOperacao

	if singular {
		var ok bool
		object, ok = maybeEventoOperacao.(*EventoOperacao)
		if !ok {
			object = new(EventoOperacao)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEventoOperacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEventoOperacao))
			}
		}
	} else {
		s, ok := maybeEventoOperacao.(*[]*EventoOperacao)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEventoOperacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEventoOperacao))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &eventoOperacaoR{}
		}
		args[object.EveNumero] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventoOperacaoR{}
			}

			args[obj.EveNumero] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`evento`),
		qm.WhereIn(`evento.eve_numero in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Evento")
	}

	var resultSlice []*Evento
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Evento")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for evento")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for evento")
	}

	if len(eventoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EveNumeroEvento = foreign
		if foreign.R == nil {
			foreign.R = &eventoR{}
		}
		foreign.R.EveNumeroEventoOperacaos = append(foreign.R.EveNumeroEventoOperacaos, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EveNumero == foreign.EveNumero {
				local.R.EveNumeroEvento = foreign
				if foreign.R == nil {
					foreign.R = &eventoR{}
				}
				foreign.R.EveNumeroEventoOperacaos = append(foreign.R.EveNumeroEventoOperacaos, local)
				break
			}
		}
	}

	return nil
}

// SetEvoEveNumeroEvento of the eventoOperacao to the related item.
// Sets o.R.EvoEveNumeroEvento to related.
// Adds o to related.R.EvoEveNumeroEventoOperacaos.
func (o *EventoOperacao) SetEvoEveNumeroEvento(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Evento) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `evento_operacao` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"evo_eve_numero"}),
		strmangle.WhereClause("`", "`", 0, eventoOperacaoPrimaryKeyColumns),
	)
	values := []interface{}{related.EveNumero, o.EveNumero, o.EvoItem}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EvoEveNumero = related.EveNumero
	if o.R == nil {
		o.R = &eventoOperacaoR{
			EvoEveNumeroEvento: related,
		}
	} else {
		o.R.EvoEveNumeroEvento = related
	}

	if related.R == nil {
		related.R = &eventoR{
			EvoEveNumeroEventoOperacaos: EventoOperacaoSlice{o},
		}
	} else {
		related.R.EvoEveNumeroEventoOperacaos = append(related.R.EvoEveNumeroEventoOperacaos, o)
	}

	return nil
}

// SetEveNumeroEvento of the eventoOperacao to the related item.
// Sets o.R.EveNumeroEvento to related.
// Adds o to related.R.EveNumeroEventoOperacaos.
func (o *EventoOperacao) SetEveNumeroEvento(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Evento) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `evento_operacao` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"eve_numero"}),
		strmangle.WhereClause("`", "`", 0, eventoOperacaoPrimaryKeyColumns),
	)
	values := []interface{}{related.EveNumero, o.EveNumero, o.EvoItem}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EveNumero = related.EveNumero
	if o.R == nil {
		o.R = &eventoOperacaoR{
			EveNumeroEvento: related,
		}
	} else {
		o.R.EveNumeroEvento = related
	}

	if related.R == nil {
		related.R = &eventoR{
			EveNumeroEventoOperacaos: EventoOperacaoSlice{o},
		}
	} else {
		related.R.EveNumeroEventoOperacaos = append(related.R.EveNumeroEventoOperacaos, o)
	}

	return nil
}

// EventoOperacaos retrieves all the records using an executor.
func EventoOperacaos(mods ...qm.QueryMod) eventoOperacaoQuery {
	mods = append(mods, qm.From("`evento_operacao`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`evento_operacao`.*"})
	}

	return eventoOperacaoQuery{q}
}

// FindEventoOperacao retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEventoOperacao(ctx context.Context, exec boil.ContextExecutor, eveNumero int, evoItem int16, selectCols ...string) (*EventoOperacao, error) {
	eventoOperacaoObj := &EventoOperacao{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `evento_operacao` where `eve_numero`=? AND `evo_item`=?", sel,
	)

	q := queries.Raw(query, eveNumero, evoItem)

	err := q.Bind(ctx, exec, eventoOperacaoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from evento_operacao")
	}

	if err = eventoOperacaoObj.doAfterSelectHooks(ctx, exec); err != nil {
		return eventoOperacaoObj, err
	}

	return eventoOperacaoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EventoOperacao) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no evento_operacao provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventoOperacaoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	eventoOperacaoInsertCacheMut.RLock()
	cache, cached := eventoOperacaoInsertCache[key]
	eventoOperacaoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			eventoOperacaoAllColumns,
			eventoOperacaoColumnsWithDefault,
			eventoOperacaoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(eventoOperacaoType, eventoOperacaoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(eventoOperacaoType, eventoOperacaoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `evento_operacao` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `evento_operacao` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `evento_operacao` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, eventoOperacaoPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into evento_operacao")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.EveNumero,
		o.EvoItem,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for evento_operacao")
	}

CacheNoHooks:
	if !cached {
		eventoOperacaoInsertCacheMut.Lock()
		eventoOperacaoInsertCache[key] = cache
		eventoOperacaoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EventoOperacao.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EventoOperacao) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	eventoOperacaoUpdateCacheMut.RLock()
	cache, cached := eventoOperacaoUpdateCache[key]
	eventoOperacaoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			eventoOperacaoAllColumns,
			eventoOperacaoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update evento_operacao, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `evento_operacao` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, eventoOperacaoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(eventoOperacaoType, eventoOperacaoMapping, append(wl, eventoOperacaoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update evento_operacao row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for evento_operacao")
	}

	if !cached {
		eventoOperacaoUpdateCacheMut.Lock()
		eventoOperacaoUpdateCache[key] = cache
		eventoOperacaoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q eventoOperacaoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for evento_operacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for evento_operacao")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EventoOperacaoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventoOperacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `evento_operacao` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, eventoOperacaoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in eventoOperacao slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all eventoOperacao")
	}
	return rowsAff, nil
}

var mySQLEventoOperacaoUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EventoOperacao) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no evento_operacao provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventoOperacaoColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLEventoOperacaoUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	eventoOperacaoUpsertCacheMut.RLock()
	cache, cached := eventoOperacaoUpsertCache[key]
	eventoOperacaoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			eventoOperacaoAllColumns,
			eventoOperacaoColumnsWithDefault,
			eventoOperacaoColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			eventoOperacaoAllColumns,
			eventoOperacaoPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert evento_operacao, could not build update column list")
		}

		ret := strmangle.SetComplement(eventoOperacaoAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`evento_operacao`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `evento_operacao` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(eventoOperacaoType, eventoOperacaoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(eventoOperacaoType, eventoOperacaoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for evento_operacao")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(eventoOperacaoType, eventoOperacaoMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for evento_operacao")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for evento_operacao")
	}

CacheNoHooks:
	if !cached {
		eventoOperacaoUpsertCacheMut.Lock()
		eventoOperacaoUpsertCache[key] = cache
		eventoOperacaoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EventoOperacao record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EventoOperacao) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EventoOperacao provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), eventoOperacaoPrimaryKeyMapping)
	sql := "DELETE FROM `evento_operacao` WHERE `eve_numero`=? AND `evo_item`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from evento_operacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for evento_operacao")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q eventoOperacaoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no eventoOperacaoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from evento_operacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for evento_operacao")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EventoOperacaoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(eventoOperacaoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventoOperacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `evento_operacao` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, eventoOperacaoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from eventoOperacao slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for evento_operacao")
	}

	if len(eventoOperacaoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EventoOperacao) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEventoOperacao(ctx, exec, o.EveNumero, o.EvoItem)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventoOperacaoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EventoOperacaoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventoOperacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `evento_operacao`.* FROM `evento_operacao` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, eventoOperacaoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EventoOperacaoSlice")
	}

	*o = slice

	return nil
}

// EventoOperacaoExists checks if the EventoOperacao row exists.
func EventoOperacaoExists(ctx context.Context, exec boil.ContextExecutor, eveNumero int, evoItem int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `evento_operacao` where `eve_numero`=? AND `evo_item`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, eveNumero, evoItem)
	}
	row := exec.QueryRowContext(ctx, sql, eveNumero, evoItem)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if evento_operacao exists")
	}

	return exists, nil
}

// Exists checks if the EventoOperacao row exists.
func (o *EventoOperacao) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EventoOperacaoExists(ctx, exec, o.EveNumero, o.EvoItem)
}
