// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Habilitacao is an object representing the database table.
type Habilitacao struct {
	HabCodigo    int16       `boil:"hab_codigo" json:"hab_codigo" toml:"hab_codigo" yaml:"hab_codigo"`
	HabDescricao null.String `boil:"hab_descricao" json:"hab_descricao,omitempty" toml:"hab_descricao" yaml:"hab_descricao,omitempty"`

	R *habilitacaoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L habilitacaoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HabilitacaoColumns = struct {
	HabCodigo    string
	HabDescricao string
}{
	HabCodigo:    "hab_codigo",
	HabDescricao: "hab_descricao",
}

var HabilitacaoTableColumns = struct {
	HabCodigo    string
	HabDescricao string
}{
	HabCodigo:    "habilitacao.hab_codigo",
	HabDescricao: "habilitacao.hab_descricao",
}

// Generated where

var HabilitacaoWhere = struct {
	HabCodigo    whereHelperint16
	HabDescricao whereHelpernull_String
}{
	HabCodigo:    whereHelperint16{field: "`habilitacao`.`hab_codigo`"},
	HabDescricao: whereHelpernull_String{field: "`habilitacao`.`hab_descricao`"},
}

// HabilitacaoRels is where relationship names are stored.
var HabilitacaoRels = struct {
	EntEntidades string
}{
	EntEntidades: "EntEntidades",
}

// habilitacaoR is where relationships are stored.
type habilitacaoR struct {
	EntEntidades EntidadeSlice `boil:"EntEntidades" json:"EntEntidades" toml:"EntEntidades" yaml:"EntEntidades"`
}

// NewStruct creates a new relationship struct
func (*habilitacaoR) NewStruct() *habilitacaoR {
	return &habilitacaoR{}
}

func (r *habilitacaoR) GetEntEntidades() EntidadeSlice {
	if r == nil {
		return nil
	}
	return r.EntEntidades
}

// habilitacaoL is where Load methods for each relationship are stored.
type habilitacaoL struct{}

var (
	habilitacaoAllColumns            = []string{"hab_codigo", "hab_descricao"}
	habilitacaoColumnsWithoutDefault = []string{"hab_codigo", "hab_descricao"}
	habilitacaoColumnsWithDefault    = []string{}
	habilitacaoPrimaryKeyColumns     = []string{"hab_codigo"}
	habilitacaoGeneratedColumns      = []string{}
)

type (
	// HabilitacaoSlice is an alias for a slice of pointers to Habilitacao.
	// This should almost always be used instead of []Habilitacao.
	HabilitacaoSlice []*Habilitacao
	// HabilitacaoHook is the signature for custom Habilitacao hook methods
	HabilitacaoHook func(context.Context, boil.ContextExecutor, *Habilitacao) error

	habilitacaoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	habilitacaoType                 = reflect.TypeOf(&Habilitacao{})
	habilitacaoMapping              = queries.MakeStructMapping(habilitacaoType)
	habilitacaoPrimaryKeyMapping, _ = queries.BindMapping(habilitacaoType, habilitacaoMapping, habilitacaoPrimaryKeyColumns)
	habilitacaoInsertCacheMut       sync.RWMutex
	habilitacaoInsertCache          = make(map[string]insertCache)
	habilitacaoUpdateCacheMut       sync.RWMutex
	habilitacaoUpdateCache          = make(map[string]updateCache)
	habilitacaoUpsertCacheMut       sync.RWMutex
	habilitacaoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var habilitacaoAfterSelectMu sync.Mutex
var habilitacaoAfterSelectHooks []HabilitacaoHook

var habilitacaoBeforeInsertMu sync.Mutex
var habilitacaoBeforeInsertHooks []HabilitacaoHook
var habilitacaoAfterInsertMu sync.Mutex
var habilitacaoAfterInsertHooks []HabilitacaoHook

var habilitacaoBeforeUpdateMu sync.Mutex
var habilitacaoBeforeUpdateHooks []HabilitacaoHook
var habilitacaoAfterUpdateMu sync.Mutex
var habilitacaoAfterUpdateHooks []HabilitacaoHook

var habilitacaoBeforeDeleteMu sync.Mutex
var habilitacaoBeforeDeleteHooks []HabilitacaoHook
var habilitacaoAfterDeleteMu sync.Mutex
var habilitacaoAfterDeleteHooks []HabilitacaoHook

var habilitacaoBeforeUpsertMu sync.Mutex
var habilitacaoBeforeUpsertHooks []HabilitacaoHook
var habilitacaoAfterUpsertMu sync.Mutex
var habilitacaoAfterUpsertHooks []HabilitacaoHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Habilitacao) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Habilitacao) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Habilitacao) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Habilitacao) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Habilitacao) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Habilitacao) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Habilitacao) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Habilitacao) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Habilitacao) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range habilitacaoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHabilitacaoHook registers your hook function for all future operations.
func AddHabilitacaoHook(hookPoint boil.HookPoint, habilitacaoHook HabilitacaoHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		habilitacaoAfterSelectMu.Lock()
		habilitacaoAfterSelectHooks = append(habilitacaoAfterSelectHooks, habilitacaoHook)
		habilitacaoAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		habilitacaoBeforeInsertMu.Lock()
		habilitacaoBeforeInsertHooks = append(habilitacaoBeforeInsertHooks, habilitacaoHook)
		habilitacaoBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		habilitacaoAfterInsertMu.Lock()
		habilitacaoAfterInsertHooks = append(habilitacaoAfterInsertHooks, habilitacaoHook)
		habilitacaoAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		habilitacaoBeforeUpdateMu.Lock()
		habilitacaoBeforeUpdateHooks = append(habilitacaoBeforeUpdateHooks, habilitacaoHook)
		habilitacaoBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		habilitacaoAfterUpdateMu.Lock()
		habilitacaoAfterUpdateHooks = append(habilitacaoAfterUpdateHooks, habilitacaoHook)
		habilitacaoAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		habilitacaoBeforeDeleteMu.Lock()
		habilitacaoBeforeDeleteHooks = append(habilitacaoBeforeDeleteHooks, habilitacaoHook)
		habilitacaoBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		habilitacaoAfterDeleteMu.Lock()
		habilitacaoAfterDeleteHooks = append(habilitacaoAfterDeleteHooks, habilitacaoHook)
		habilitacaoAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		habilitacaoBeforeUpsertMu.Lock()
		habilitacaoBeforeUpsertHooks = append(habilitacaoBeforeUpsertHooks, habilitacaoHook)
		habilitacaoBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		habilitacaoAfterUpsertMu.Lock()
		habilitacaoAfterUpsertHooks = append(habilitacaoAfterUpsertHooks, habilitacaoHook)
		habilitacaoAfterUpsertMu.Unlock()
	}
}

// One returns a single habilitacao record from the query.
func (q habilitacaoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Habilitacao, error) {
	o := &Habilitacao{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for habilitacao")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Habilitacao records from the query.
func (q habilitacaoQuery) All(ctx context.Context, exec boil.ContextExecutor) (HabilitacaoSlice, error) {
	var o []*Habilitacao

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Habilitacao slice")
	}

	if len(habilitacaoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Habilitacao records in the query.
func (q habilitacaoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count habilitacao rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q habilitacaoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if habilitacao exists")
	}

	return count > 0, nil
}

// EntEntidades retrieves all the entidade's Entidades with an executor via ent_id column.
func (o *Habilitacao) EntEntidades(mods ...qm.QueryMod) entidadeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("`entidade_habilitacao` on `entidade`.`ent_id` = `entidade_habilitacao`.`ent_id`"),
		qm.Where("`entidade_habilitacao`.`hab_codigo`=?", o.HabCodigo),
	)

	return Entidades(queryMods...)
}

// LoadEntEntidades allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (habilitacaoL) LoadEntEntidades(ctx context.Context, e boil.ContextExecutor, singular bool, maybeHabilitacao interface{}, mods queries.Applicator) error {
	var slice []*Habilitacao
	var object *Habilitacao

	if singular {
		var ok bool
		object, ok = maybeHabilitacao.(*Habilitacao)
		if !ok {
			object = new(Habilitacao)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeHabilitacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeHabilitacao))
			}
		}
	} else {
		s, ok := maybeHabilitacao.(*[]*Habilitacao)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeHabilitacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeHabilitacao))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &habilitacaoR{}
		}
		args[object.HabCodigo] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &habilitacaoR{}
			}
			args[obj.HabCodigo] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("`entidade`.`ent_id`, `entidade`.`gpe_id`, `entidade`.`ent_trans_id`, `entidade`.`emf_id`, `entidade`.`tbp_id`, `entidade`.`ent_codigo`, `entidade`.`ent_tipopessoa`, `entidade`.`ent_razaosocial`, `entidade`.`ent_nomefantasia`, `entidade`.`ent_inscricaofederal`, `entidade`.`ent_inscricaoestadual`, `entidade`.`ent_inscricaoprodutor`, `entidade`.`ent_situacao`, `entidade`.`ent_classificacao`, `entidade`.`ent_observacao`, `entidade`.`ent_suframa`, `entidade`.`ent_inscricaomunicipal`, `entidade`.`ent_datanascimento`, `entidade`.`ent_nomedamae`, `entidade`.`ent_nomedopai`, `entidade`.`ent_sexo`, `entidade`.`ent_casapropria`, `entidade`.`ent_estadocivil`, `entidade`.`ent_conjuje_nome`, `entidade`.`ent_conjuje_cpf`, `entidade`.`ent_conjuje_renda`, `entidade`.`ent_conjuje_rg`, `entidade`.`ent_quantfilhos`, `entidade`.`ent_datacadastro`, `entidade`.`hor_id`, `entidade`.`tdesc_id`, `entidade`.`ent_percentualcomissao`, `entidade`.`ent_taxaentrega`, `entidade`.`ent_arq_imp_ddv`, `a`.`hab_codigo`"),
		qm.From("`entidade`"),
		qm.InnerJoin("`entidade_habilitacao` as `a` on `entidade`.`ent_id` = `a`.`ent_id`"),
		qm.WhereIn("`a`.`hab_codigo` in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load entidade")
	}

	var resultSlice []*Entidade

	var localJoinCols []int16
	for results.Next() {
		one := new(Entidade)
		var localJoinCol int16

		err = results.Scan(&one.EntID, &one.GpeID, &one.EntTransID, &one.EmfID, &one.TBPID, &one.EntCodigo, &one.EntTipopessoa, &one.EntRazaosocial, &one.EntNomefantasia, &one.EntInscricaofederal, &one.EntInscricaoestadual, &one.EntInscricaoprodutor, &one.EntSituacao, &one.EntClassificacao, &one.EntObservacao, &one.EntSuframa, &one.EntInscricaomunicipal, &one.EntDatanascimento, &one.EntNomedamae, &one.EntNomedopai, &one.EntSexo, &one.EntCasapropria, &one.EntEstadocivil, &one.EntConjujeNome, &one.EntConjujeCPF, &one.EntConjujeRenda, &one.EntConjujeRG, &one.EntQuantfilhos, &one.EntDatacadastro, &one.HorID, &one.TdescID, &one.EntPercentualcomissao, &one.EntTaxaentrega, &one.EntArqImpDDV, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for entidade")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice entidade")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on entidade")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for entidade")
	}

	if len(entidadeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.EntEntidades = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &entidadeR{}
			}
			foreign.R.HabCodigoHabilitacaos = append(foreign.R.HabCodigoHabilitacaos, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.HabCodigo == localJoinCol {
				local.R.EntEntidades = append(local.R.EntEntidades, foreign)
				if foreign.R == nil {
					foreign.R = &entidadeR{}
				}
				foreign.R.HabCodigoHabilitacaos = append(foreign.R.HabCodigoHabilitacaos, local)
				break
			}
		}
	}

	return nil
}

// AddEntEntidades adds the given related objects to the existing relationships
// of the habilitacao, optionally inserting them as new records.
// Appends related to o.R.EntEntidades.
// Sets related.R.HabCodigoHabilitacaos appropriately.
func (o *Habilitacao) AddEntEntidades(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Entidade) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into `entidade_habilitacao` (`hab_codigo`, `ent_id`) values (?, ?)"
		values := []interface{}{o.HabCodigo, rel.EntID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &habilitacaoR{
			EntEntidades: related,
		}
	} else {
		o.R.EntEntidades = append(o.R.EntEntidades, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &entidadeR{
				HabCodigoHabilitacaos: HabilitacaoSlice{o},
			}
		} else {
			rel.R.HabCodigoHabilitacaos = append(rel.R.HabCodigoHabilitacaos, o)
		}
	}
	return nil
}

// SetEntEntidades removes all previously related items of the
// habilitacao replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.HabCodigoHabilitacaos's EntEntidades accordingly.
// Replaces o.R.EntEntidades with related.
// Sets related.R.HabCodigoHabilitacaos's EntEntidades accordingly.
func (o *Habilitacao) SetEntEntidades(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Entidade) error {
	query := "delete from `entidade_habilitacao` where `hab_codigo` = ?"
	values := []interface{}{o.HabCodigo}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeEntEntidadesFromHabCodigoHabilitacaosSlice(o, related)
	if o.R != nil {
		o.R.EntEntidades = nil
	}

	return o.AddEntEntidades(ctx, exec, insert, related...)
}

// RemoveEntEntidades relationships from objects passed in.
// Removes related items from R.EntEntidades (uses pointer comparison, removal does not keep order)
// Sets related.R.HabCodigoHabilitacaos.
func (o *Habilitacao) RemoveEntEntidades(ctx context.Context, exec boil.ContextExecutor, related ...*Entidade) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from `entidade_habilitacao` where `hab_codigo` = ? and `ent_id` in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.HabCodigo}
	for _, rel := range related {
		values = append(values, rel.EntID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeEntEntidadesFromHabCodigoHabilitacaosSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.EntEntidades {
			if rel != ri {
				continue
			}

			ln := len(o.R.EntEntidades)
			if ln > 1 && i < ln-1 {
				o.R.EntEntidades[i] = o.R.EntEntidades[ln-1]
			}
			o.R.EntEntidades = o.R.EntEntidades[:ln-1]
			break
		}
	}

	return nil
}

func removeEntEntidadesFromHabCodigoHabilitacaosSlice(o *Habilitacao, related []*Entidade) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.HabCodigoHabilitacaos {
			if o.HabCodigo != ri.HabCodigo {
				continue
			}

			ln := len(rel.R.HabCodigoHabilitacaos)
			if ln > 1 && i < ln-1 {
				rel.R.HabCodigoHabilitacaos[i] = rel.R.HabCodigoHabilitacaos[ln-1]
			}
			rel.R.HabCodigoHabilitacaos = rel.R.HabCodigoHabilitacaos[:ln-1]
			break
		}
	}
}

// Habilitacaos retrieves all the records using an executor.
func Habilitacaos(mods ...qm.QueryMod) habilitacaoQuery {
	mods = append(mods, qm.From("`habilitacao`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`habilitacao`.*"})
	}

	return habilitacaoQuery{q}
}

// FindHabilitacao retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHabilitacao(ctx context.Context, exec boil.ContextExecutor, habCodigo int16, selectCols ...string) (*Habilitacao, error) {
	habilitacaoObj := &Habilitacao{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `habilitacao` where `hab_codigo`=?", sel,
	)

	q := queries.Raw(query, habCodigo)

	err := q.Bind(ctx, exec, habilitacaoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from habilitacao")
	}

	if err = habilitacaoObj.doAfterSelectHooks(ctx, exec); err != nil {
		return habilitacaoObj, err
	}

	return habilitacaoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Habilitacao) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no habilitacao provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(habilitacaoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	habilitacaoInsertCacheMut.RLock()
	cache, cached := habilitacaoInsertCache[key]
	habilitacaoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			habilitacaoAllColumns,
			habilitacaoColumnsWithDefault,
			habilitacaoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(habilitacaoType, habilitacaoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(habilitacaoType, habilitacaoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `habilitacao` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `habilitacao` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `habilitacao` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, habilitacaoPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into habilitacao")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.HabCodigo,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for habilitacao")
	}

CacheNoHooks:
	if !cached {
		habilitacaoInsertCacheMut.Lock()
		habilitacaoInsertCache[key] = cache
		habilitacaoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Habilitacao.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Habilitacao) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	habilitacaoUpdateCacheMut.RLock()
	cache, cached := habilitacaoUpdateCache[key]
	habilitacaoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			habilitacaoAllColumns,
			habilitacaoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update habilitacao, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `habilitacao` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, habilitacaoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(habilitacaoType, habilitacaoMapping, append(wl, habilitacaoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update habilitacao row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for habilitacao")
	}

	if !cached {
		habilitacaoUpdateCacheMut.Lock()
		habilitacaoUpdateCache[key] = cache
		habilitacaoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q habilitacaoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for habilitacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for habilitacao")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HabilitacaoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), habilitacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `habilitacao` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, habilitacaoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in habilitacao slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all habilitacao")
	}
	return rowsAff, nil
}

var mySQLHabilitacaoUniqueColumns = []string{
	"hab_codigo",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Habilitacao) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no habilitacao provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(habilitacaoColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLHabilitacaoUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	habilitacaoUpsertCacheMut.RLock()
	cache, cached := habilitacaoUpsertCache[key]
	habilitacaoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			habilitacaoAllColumns,
			habilitacaoColumnsWithDefault,
			habilitacaoColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			habilitacaoAllColumns,
			habilitacaoPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert habilitacao, could not build update column list")
		}

		ret := strmangle.SetComplement(habilitacaoAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`habilitacao`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `habilitacao` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(habilitacaoType, habilitacaoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(habilitacaoType, habilitacaoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for habilitacao")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(habilitacaoType, habilitacaoMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for habilitacao")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for habilitacao")
	}

CacheNoHooks:
	if !cached {
		habilitacaoUpsertCacheMut.Lock()
		habilitacaoUpsertCache[key] = cache
		habilitacaoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Habilitacao record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Habilitacao) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Habilitacao provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), habilitacaoPrimaryKeyMapping)
	sql := "DELETE FROM `habilitacao` WHERE `hab_codigo`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from habilitacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for habilitacao")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q habilitacaoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no habilitacaoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from habilitacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for habilitacao")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HabilitacaoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(habilitacaoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), habilitacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `habilitacao` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, habilitacaoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from habilitacao slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for habilitacao")
	}

	if len(habilitacaoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Habilitacao) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindHabilitacao(ctx, exec, o.HabCodigo)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HabilitacaoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HabilitacaoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), habilitacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `habilitacao`.* FROM `habilitacao` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, habilitacaoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in HabilitacaoSlice")
	}

	*o = slice

	return nil
}

// HabilitacaoExists checks if the Habilitacao row exists.
func HabilitacaoExists(ctx context.Context, exec boil.ContextExecutor, habCodigo int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `habilitacao` where `hab_codigo`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, habCodigo)
	}
	row := exec.QueryRowContext(ctx, sql, habCodigo)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if habilitacao exists")
	}

	return exists, nil
}

// Exists checks if the Habilitacao row exists.
func (o *Habilitacao) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return HabilitacaoExists(ctx, exec, o.HabCodigo)
}
