// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// NotaFiscalSituacao is an object representing the database table.
type NotaFiscalSituacao struct {
	NfsitID        int16  `boil:"nfsit_id" json:"nfsit_id" toml:"nfsit_id" yaml:"nfsit_id"`
	NfsitDescricao string `boil:"nfsit_descricao" json:"nfsit_descricao" toml:"nfsit_descricao" yaml:"nfsit_descricao"`

	R *notaFiscalSituacaoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L notaFiscalSituacaoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NotaFiscalSituacaoColumns = struct {
	NfsitID        string
	NfsitDescricao string
}{
	NfsitID:        "nfsit_id",
	NfsitDescricao: "nfsit_descricao",
}

var NotaFiscalSituacaoTableColumns = struct {
	NfsitID        string
	NfsitDescricao string
}{
	NfsitID:        "nota_fiscal_situacao.nfsit_id",
	NfsitDescricao: "nota_fiscal_situacao.nfsit_descricao",
}

// Generated where

var NotaFiscalSituacaoWhere = struct {
	NfsitID        whereHelperint16
	NfsitDescricao whereHelperstring
}{
	NfsitID:        whereHelperint16{field: "`nota_fiscal_situacao`.`nfsit_id`"},
	NfsitDescricao: whereHelperstring{field: "`nota_fiscal_situacao`.`nfsit_descricao`"},
}

// NotaFiscalSituacaoRels is where relationship names are stored.
var NotaFiscalSituacaoRels = struct {
	NfsitNotaFiscals string
}{
	NfsitNotaFiscals: "NfsitNotaFiscals",
}

// notaFiscalSituacaoR is where relationships are stored.
type notaFiscalSituacaoR struct {
	NfsitNotaFiscals NotaFiscalSlice `boil:"NfsitNotaFiscals" json:"NfsitNotaFiscals" toml:"NfsitNotaFiscals" yaml:"NfsitNotaFiscals"`
}

// NewStruct creates a new relationship struct
func (*notaFiscalSituacaoR) NewStruct() *notaFiscalSituacaoR {
	return &notaFiscalSituacaoR{}
}

func (r *notaFiscalSituacaoR) GetNfsitNotaFiscals() NotaFiscalSlice {
	if r == nil {
		return nil
	}
	return r.NfsitNotaFiscals
}

// notaFiscalSituacaoL is where Load methods for each relationship are stored.
type notaFiscalSituacaoL struct{}

var (
	notaFiscalSituacaoAllColumns            = []string{"nfsit_id", "nfsit_descricao"}
	notaFiscalSituacaoColumnsWithoutDefault = []string{"nfsit_id", "nfsit_descricao"}
	notaFiscalSituacaoColumnsWithDefault    = []string{}
	notaFiscalSituacaoPrimaryKeyColumns     = []string{"nfsit_id"}
	notaFiscalSituacaoGeneratedColumns      = []string{}
)

type (
	// NotaFiscalSituacaoSlice is an alias for a slice of pointers to NotaFiscalSituacao.
	// This should almost always be used instead of []NotaFiscalSituacao.
	NotaFiscalSituacaoSlice []*NotaFiscalSituacao
	// NotaFiscalSituacaoHook is the signature for custom NotaFiscalSituacao hook methods
	NotaFiscalSituacaoHook func(context.Context, boil.ContextExecutor, *NotaFiscalSituacao) error

	notaFiscalSituacaoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	notaFiscalSituacaoType                 = reflect.TypeOf(&NotaFiscalSituacao{})
	notaFiscalSituacaoMapping              = queries.MakeStructMapping(notaFiscalSituacaoType)
	notaFiscalSituacaoPrimaryKeyMapping, _ = queries.BindMapping(notaFiscalSituacaoType, notaFiscalSituacaoMapping, notaFiscalSituacaoPrimaryKeyColumns)
	notaFiscalSituacaoInsertCacheMut       sync.RWMutex
	notaFiscalSituacaoInsertCache          = make(map[string]insertCache)
	notaFiscalSituacaoUpdateCacheMut       sync.RWMutex
	notaFiscalSituacaoUpdateCache          = make(map[string]updateCache)
	notaFiscalSituacaoUpsertCacheMut       sync.RWMutex
	notaFiscalSituacaoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var notaFiscalSituacaoAfterSelectMu sync.Mutex
var notaFiscalSituacaoAfterSelectHooks []NotaFiscalSituacaoHook

var notaFiscalSituacaoBeforeInsertMu sync.Mutex
var notaFiscalSituacaoBeforeInsertHooks []NotaFiscalSituacaoHook
var notaFiscalSituacaoAfterInsertMu sync.Mutex
var notaFiscalSituacaoAfterInsertHooks []NotaFiscalSituacaoHook

var notaFiscalSituacaoBeforeUpdateMu sync.Mutex
var notaFiscalSituacaoBeforeUpdateHooks []NotaFiscalSituacaoHook
var notaFiscalSituacaoAfterUpdateMu sync.Mutex
var notaFiscalSituacaoAfterUpdateHooks []NotaFiscalSituacaoHook

var notaFiscalSituacaoBeforeDeleteMu sync.Mutex
var notaFiscalSituacaoBeforeDeleteHooks []NotaFiscalSituacaoHook
var notaFiscalSituacaoAfterDeleteMu sync.Mutex
var notaFiscalSituacaoAfterDeleteHooks []NotaFiscalSituacaoHook

var notaFiscalSituacaoBeforeUpsertMu sync.Mutex
var notaFiscalSituacaoBeforeUpsertHooks []NotaFiscalSituacaoHook
var notaFiscalSituacaoAfterUpsertMu sync.Mutex
var notaFiscalSituacaoAfterUpsertHooks []NotaFiscalSituacaoHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *NotaFiscalSituacao) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *NotaFiscalSituacao) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *NotaFiscalSituacao) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *NotaFiscalSituacao) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *NotaFiscalSituacao) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *NotaFiscalSituacao) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *NotaFiscalSituacao) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *NotaFiscalSituacao) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *NotaFiscalSituacao) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notaFiscalSituacaoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddNotaFiscalSituacaoHook registers your hook function for all future operations.
func AddNotaFiscalSituacaoHook(hookPoint boil.HookPoint, notaFiscalSituacaoHook NotaFiscalSituacaoHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		notaFiscalSituacaoAfterSelectMu.Lock()
		notaFiscalSituacaoAfterSelectHooks = append(notaFiscalSituacaoAfterSelectHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		notaFiscalSituacaoBeforeInsertMu.Lock()
		notaFiscalSituacaoBeforeInsertHooks = append(notaFiscalSituacaoBeforeInsertHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		notaFiscalSituacaoAfterInsertMu.Lock()
		notaFiscalSituacaoAfterInsertHooks = append(notaFiscalSituacaoAfterInsertHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		notaFiscalSituacaoBeforeUpdateMu.Lock()
		notaFiscalSituacaoBeforeUpdateHooks = append(notaFiscalSituacaoBeforeUpdateHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		notaFiscalSituacaoAfterUpdateMu.Lock()
		notaFiscalSituacaoAfterUpdateHooks = append(notaFiscalSituacaoAfterUpdateHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		notaFiscalSituacaoBeforeDeleteMu.Lock()
		notaFiscalSituacaoBeforeDeleteHooks = append(notaFiscalSituacaoBeforeDeleteHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		notaFiscalSituacaoAfterDeleteMu.Lock()
		notaFiscalSituacaoAfterDeleteHooks = append(notaFiscalSituacaoAfterDeleteHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		notaFiscalSituacaoBeforeUpsertMu.Lock()
		notaFiscalSituacaoBeforeUpsertHooks = append(notaFiscalSituacaoBeforeUpsertHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		notaFiscalSituacaoAfterUpsertMu.Lock()
		notaFiscalSituacaoAfterUpsertHooks = append(notaFiscalSituacaoAfterUpsertHooks, notaFiscalSituacaoHook)
		notaFiscalSituacaoAfterUpsertMu.Unlock()
	}
}

// One returns a single notaFiscalSituacao record from the query.
func (q notaFiscalSituacaoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NotaFiscalSituacao, error) {
	o := &NotaFiscalSituacao{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for nota_fiscal_situacao")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all NotaFiscalSituacao records from the query.
func (q notaFiscalSituacaoQuery) All(ctx context.Context, exec boil.ContextExecutor) (NotaFiscalSituacaoSlice, error) {
	var o []*NotaFiscalSituacao

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NotaFiscalSituacao slice")
	}

	if len(notaFiscalSituacaoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all NotaFiscalSituacao records in the query.
func (q notaFiscalSituacaoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count nota_fiscal_situacao rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q notaFiscalSituacaoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if nota_fiscal_situacao exists")
	}

	return count > 0, nil
}

// NfsitNotaFiscals retrieves all the nota_fiscal's NotaFiscals with an executor via nfsit_id column.
func (o *NotaFiscalSituacao) NfsitNotaFiscals(mods ...qm.QueryMod) notaFiscalQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`nota_fiscal`.`nfsit_id`=?", o.NfsitID),
	)

	return NotaFiscals(queryMods...)
}

// LoadNfsitNotaFiscals allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (notaFiscalSituacaoL) LoadNfsitNotaFiscals(ctx context.Context, e boil.ContextExecutor, singular bool, maybeNotaFiscalSituacao interface{}, mods queries.Applicator) error {
	var slice []*NotaFiscalSituacao
	var object *NotaFiscalSituacao

	if singular {
		var ok bool
		object, ok = maybeNotaFiscalSituacao.(*NotaFiscalSituacao)
		if !ok {
			object = new(NotaFiscalSituacao)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeNotaFiscalSituacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeNotaFiscalSituacao))
			}
		}
	} else {
		s, ok := maybeNotaFiscalSituacao.(*[]*NotaFiscalSituacao)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeNotaFiscalSituacao)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeNotaFiscalSituacao))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &notaFiscalSituacaoR{}
		}
		args[object.NfsitID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &notaFiscalSituacaoR{}
			}
			args[obj.NfsitID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`nota_fiscal`),
		qm.WhereIn(`nota_fiscal.nfsit_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load nota_fiscal")
	}

	var resultSlice []*NotaFiscal
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice nota_fiscal")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on nota_fiscal")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for nota_fiscal")
	}

	if len(notaFiscalAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.NfsitNotaFiscals = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &notaFiscalR{}
			}
			foreign.R.Nfsit = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.NfsitID == foreign.NfsitID {
				local.R.NfsitNotaFiscals = append(local.R.NfsitNotaFiscals, foreign)
				if foreign.R == nil {
					foreign.R = &notaFiscalR{}
				}
				foreign.R.Nfsit = local
				break
			}
		}
	}

	return nil
}

// AddNfsitNotaFiscals adds the given related objects to the existing relationships
// of the nota_fiscal_situacao, optionally inserting them as new records.
// Appends related to o.R.NfsitNotaFiscals.
// Sets related.R.Nfsit appropriately.
func (o *NotaFiscalSituacao) AddNfsitNotaFiscals(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*NotaFiscal) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.NfsitID = o.NfsitID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `nota_fiscal` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"nfsit_id"}),
				strmangle.WhereClause("`", "`", 0, notaFiscalPrimaryKeyColumns),
			)
			values := []interface{}{o.NfsitID, rel.NTFID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.NfsitID = o.NfsitID
		}
	}

	if o.R == nil {
		o.R = &notaFiscalSituacaoR{
			NfsitNotaFiscals: related,
		}
	} else {
		o.R.NfsitNotaFiscals = append(o.R.NfsitNotaFiscals, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &notaFiscalR{
				Nfsit: o,
			}
		} else {
			rel.R.Nfsit = o
		}
	}
	return nil
}

// NotaFiscalSituacaos retrieves all the records using an executor.
func NotaFiscalSituacaos(mods ...qm.QueryMod) notaFiscalSituacaoQuery {
	mods = append(mods, qm.From("`nota_fiscal_situacao`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`nota_fiscal_situacao`.*"})
	}

	return notaFiscalSituacaoQuery{q}
}

// FindNotaFiscalSituacao retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNotaFiscalSituacao(ctx context.Context, exec boil.ContextExecutor, nfsitID int16, selectCols ...string) (*NotaFiscalSituacao, error) {
	notaFiscalSituacaoObj := &NotaFiscalSituacao{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `nota_fiscal_situacao` where `nfsit_id`=?", sel,
	)

	q := queries.Raw(query, nfsitID)

	err := q.Bind(ctx, exec, notaFiscalSituacaoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from nota_fiscal_situacao")
	}

	if err = notaFiscalSituacaoObj.doAfterSelectHooks(ctx, exec); err != nil {
		return notaFiscalSituacaoObj, err
	}

	return notaFiscalSituacaoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NotaFiscalSituacao) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no nota_fiscal_situacao provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notaFiscalSituacaoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	notaFiscalSituacaoInsertCacheMut.RLock()
	cache, cached := notaFiscalSituacaoInsertCache[key]
	notaFiscalSituacaoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			notaFiscalSituacaoAllColumns,
			notaFiscalSituacaoColumnsWithDefault,
			notaFiscalSituacaoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(notaFiscalSituacaoType, notaFiscalSituacaoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(notaFiscalSituacaoType, notaFiscalSituacaoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `nota_fiscal_situacao` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `nota_fiscal_situacao` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `nota_fiscal_situacao` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, notaFiscalSituacaoPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into nota_fiscal_situacao")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.NfsitID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for nota_fiscal_situacao")
	}

CacheNoHooks:
	if !cached {
		notaFiscalSituacaoInsertCacheMut.Lock()
		notaFiscalSituacaoInsertCache[key] = cache
		notaFiscalSituacaoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the NotaFiscalSituacao.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NotaFiscalSituacao) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	notaFiscalSituacaoUpdateCacheMut.RLock()
	cache, cached := notaFiscalSituacaoUpdateCache[key]
	notaFiscalSituacaoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			notaFiscalSituacaoAllColumns,
			notaFiscalSituacaoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update nota_fiscal_situacao, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `nota_fiscal_situacao` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, notaFiscalSituacaoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(notaFiscalSituacaoType, notaFiscalSituacaoMapping, append(wl, notaFiscalSituacaoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update nota_fiscal_situacao row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for nota_fiscal_situacao")
	}

	if !cached {
		notaFiscalSituacaoUpdateCacheMut.Lock()
		notaFiscalSituacaoUpdateCache[key] = cache
		notaFiscalSituacaoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q notaFiscalSituacaoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for nota_fiscal_situacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for nota_fiscal_situacao")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NotaFiscalSituacaoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notaFiscalSituacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `nota_fiscal_situacao` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notaFiscalSituacaoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in notaFiscalSituacao slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all notaFiscalSituacao")
	}
	return rowsAff, nil
}

var mySQLNotaFiscalSituacaoUniqueColumns = []string{
	"nfsit_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NotaFiscalSituacao) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no nota_fiscal_situacao provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notaFiscalSituacaoColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLNotaFiscalSituacaoUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	notaFiscalSituacaoUpsertCacheMut.RLock()
	cache, cached := notaFiscalSituacaoUpsertCache[key]
	notaFiscalSituacaoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			notaFiscalSituacaoAllColumns,
			notaFiscalSituacaoColumnsWithDefault,
			notaFiscalSituacaoColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			notaFiscalSituacaoAllColumns,
			notaFiscalSituacaoPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert nota_fiscal_situacao, could not build update column list")
		}

		ret := strmangle.SetComplement(notaFiscalSituacaoAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`nota_fiscal_situacao`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `nota_fiscal_situacao` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(notaFiscalSituacaoType, notaFiscalSituacaoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(notaFiscalSituacaoType, notaFiscalSituacaoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for nota_fiscal_situacao")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(notaFiscalSituacaoType, notaFiscalSituacaoMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for nota_fiscal_situacao")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for nota_fiscal_situacao")
	}

CacheNoHooks:
	if !cached {
		notaFiscalSituacaoUpsertCacheMut.Lock()
		notaFiscalSituacaoUpsertCache[key] = cache
		notaFiscalSituacaoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single NotaFiscalSituacao record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NotaFiscalSituacao) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NotaFiscalSituacao provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), notaFiscalSituacaoPrimaryKeyMapping)
	sql := "DELETE FROM `nota_fiscal_situacao` WHERE `nfsit_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from nota_fiscal_situacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for nota_fiscal_situacao")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q notaFiscalSituacaoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no notaFiscalSituacaoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from nota_fiscal_situacao")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for nota_fiscal_situacao")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NotaFiscalSituacaoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(notaFiscalSituacaoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notaFiscalSituacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `nota_fiscal_situacao` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notaFiscalSituacaoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from notaFiscalSituacao slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for nota_fiscal_situacao")
	}

	if len(notaFiscalSituacaoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NotaFiscalSituacao) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNotaFiscalSituacao(ctx, exec, o.NfsitID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotaFiscalSituacaoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NotaFiscalSituacaoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notaFiscalSituacaoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `nota_fiscal_situacao`.* FROM `nota_fiscal_situacao` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notaFiscalSituacaoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NotaFiscalSituacaoSlice")
	}

	*o = slice

	return nil
}

// NotaFiscalSituacaoExists checks if the NotaFiscalSituacao row exists.
func NotaFiscalSituacaoExists(ctx context.Context, exec boil.ContextExecutor, nfsitID int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `nota_fiscal_situacao` where `nfsit_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, nfsitID)
	}
	row := exec.QueryRowContext(ctx, sql, nfsitID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if nota_fiscal_situacao exists")
	}

	return exists, nil
}

// Exists checks if the NotaFiscalSituacao row exists.
func (o *NotaFiscalSituacao) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return NotaFiscalSituacaoExists(ctx, exec, o.NfsitID)
}
