// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOrcamentoFormaPagamentos(t *testing.T) {
	t.Parallel()

	query := OrcamentoFormaPagamentos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOrcamentoFormaPagamentosDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrcamentoFormaPagamentosQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OrcamentoFormaPagamentos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrcamentoFormaPagamentosSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrcamentoFormaPagamentoSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrcamentoFormaPagamentosExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OrcamentoFormaPagamentoExists(ctx, tx, o.OrcID, o.OfpItem)
	if err != nil {
		t.Errorf("Unable to check if OrcamentoFormaPagamento exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OrcamentoFormaPagamentoExists to return true, but got false.")
	}
}

func testOrcamentoFormaPagamentosFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	orcamentoFormaPagamentoFound, err := FindOrcamentoFormaPagamento(ctx, tx, o.OrcID, o.OfpItem)
	if err != nil {
		t.Error(err)
	}

	if orcamentoFormaPagamentoFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOrcamentoFormaPagamentosBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OrcamentoFormaPagamentos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOrcamentoFormaPagamentosOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OrcamentoFormaPagamentos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOrcamentoFormaPagamentosAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	orcamentoFormaPagamentoOne := &OrcamentoFormaPagamento{}
	orcamentoFormaPagamentoTwo := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, orcamentoFormaPagamentoOne, orcamentoFormaPagamentoDBTypes, false, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}
	if err = randomize.Struct(seed, orcamentoFormaPagamentoTwo, orcamentoFormaPagamentoDBTypes, false, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orcamentoFormaPagamentoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orcamentoFormaPagamentoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrcamentoFormaPagamentos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOrcamentoFormaPagamentosCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	orcamentoFormaPagamentoOne := &OrcamentoFormaPagamento{}
	orcamentoFormaPagamentoTwo := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, orcamentoFormaPagamentoOne, orcamentoFormaPagamentoDBTypes, false, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}
	if err = randomize.Struct(seed, orcamentoFormaPagamentoTwo, orcamentoFormaPagamentoDBTypes, false, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orcamentoFormaPagamentoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orcamentoFormaPagamentoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func orcamentoFormaPagamentoBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func orcamentoFormaPagamentoAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OrcamentoFormaPagamento) error {
	*o = OrcamentoFormaPagamento{}
	return nil
}

func testOrcamentoFormaPagamentosHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &OrcamentoFormaPagamento{}
	o := &OrcamentoFormaPagamento{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento object: %s", err)
	}

	AddOrcamentoFormaPagamentoHook(boil.BeforeInsertHook, orcamentoFormaPagamentoBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoBeforeInsertHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.AfterInsertHook, orcamentoFormaPagamentoAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoAfterInsertHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.AfterSelectHook, orcamentoFormaPagamentoAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoAfterSelectHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.BeforeUpdateHook, orcamentoFormaPagamentoBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoBeforeUpdateHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.AfterUpdateHook, orcamentoFormaPagamentoAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoAfterUpdateHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.BeforeDeleteHook, orcamentoFormaPagamentoBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoBeforeDeleteHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.AfterDeleteHook, orcamentoFormaPagamentoAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoAfterDeleteHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.BeforeUpsertHook, orcamentoFormaPagamentoBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoBeforeUpsertHooks = []OrcamentoFormaPagamentoHook{}

	AddOrcamentoFormaPagamentoHook(boil.AfterUpsertHook, orcamentoFormaPagamentoAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	orcamentoFormaPagamentoAfterUpsertHooks = []OrcamentoFormaPagamentoHook{}
}

func testOrcamentoFormaPagamentosInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrcamentoFormaPagamentosInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(orcamentoFormaPagamentoColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrcamentoFormaPagamentoToOneOrcamentoCompraUsingOrc(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local OrcamentoFormaPagamento
	var foreign OrcamentoCompra

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, orcamentoFormaPagamentoDBTypes, false, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, orcamentoCompraDBTypes, false, orcamentoCompraColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoCompra struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.OrcID = foreign.OrcID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Orc().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.OrcID != foreign.OrcID {
		t.Errorf("want: %v, got %v", foreign.OrcID, check.OrcID)
	}

	ranAfterSelectHook := false
	AddOrcamentoCompraHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *OrcamentoCompra) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := OrcamentoFormaPagamentoSlice{&local}
	if err = local.L.LoadOrc(ctx, tx, false, (*[]*OrcamentoFormaPagamento)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Orc == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Orc = nil
	if err = local.L.LoadOrc(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Orc == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testOrcamentoFormaPagamentoToOneSetOpOrcamentoCompraUsingOrc(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a OrcamentoFormaPagamento
	var b, c OrcamentoCompra

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, orcamentoFormaPagamentoDBTypes, false, strmangle.SetComplement(orcamentoFormaPagamentoPrimaryKeyColumns, orcamentoFormaPagamentoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, orcamentoCompraDBTypes, false, strmangle.SetComplement(orcamentoCompraPrimaryKeyColumns, orcamentoCompraColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, orcamentoCompraDBTypes, false, strmangle.SetComplement(orcamentoCompraPrimaryKeyColumns, orcamentoCompraColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*OrcamentoCompra{&b, &c} {
		err = a.SetOrc(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Orc != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.OrcOrcamentoFormaPagamentos[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.OrcID != x.OrcID {
			t.Error("foreign key was wrong value", a.OrcID)
		}

		if exists, err := OrcamentoFormaPagamentoExists(ctx, tx, a.OrcID, a.OfpItem); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testOrcamentoFormaPagamentosReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrcamentoFormaPagamentosReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrcamentoFormaPagamentoSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrcamentoFormaPagamentosSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrcamentoFormaPagamentos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	orcamentoFormaPagamentoDBTypes = map[string]string{`OrcID`: `int`, `OfpItem`: `smallint`, `OfpDias`: `smallint`}
	_                              = bytes.MinRead
)

func testOrcamentoFormaPagamentosUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(orcamentoFormaPagamentoPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(orcamentoFormaPagamentoAllColumns) == len(orcamentoFormaPagamentoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOrcamentoFormaPagamentosSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(orcamentoFormaPagamentoAllColumns) == len(orcamentoFormaPagamentoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orcamentoFormaPagamentoDBTypes, true, orcamentoFormaPagamentoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(orcamentoFormaPagamentoAllColumns, orcamentoFormaPagamentoPrimaryKeyColumns) {
		fields = orcamentoFormaPagamentoAllColumns
	} else {
		fields = strmangle.SetComplement(
			orcamentoFormaPagamentoAllColumns,
			orcamentoFormaPagamentoPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OrcamentoFormaPagamentoSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOrcamentoFormaPagamentosUpsert(t *testing.T) {
	t.Parallel()

	if len(orcamentoFormaPagamentoAllColumns) == len(orcamentoFormaPagamentoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLOrcamentoFormaPagamentoUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OrcamentoFormaPagamento{}
	if err = randomize.Struct(seed, &o, orcamentoFormaPagamentoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrcamentoFormaPagamento: %s", err)
	}

	count, err := OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, orcamentoFormaPagamentoDBTypes, false, orcamentoFormaPagamentoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrcamentoFormaPagamento struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrcamentoFormaPagamento: %s", err)
	}

	count, err = OrcamentoFormaPagamentos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
