// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// OrcamentoVendaOperacional is an object representing the database table.
type OrcamentoVendaOperacional struct {
	OrcvID                  int           `boil:"orcv_id" json:"orcv_id" toml:"orcv_id" yaml:"orcv_id"`
	OrcvoItem               int           `boil:"orcvo_item" json:"orcvo_item" toml:"orcvo_item" yaml:"orcvo_item"`
	DespID                  int           `boil:"desp_id" json:"desp_id" toml:"desp_id" yaml:"desp_id"`
	OrcvoValorcustounitario types.Decimal `boil:"orcvo_valorcustounitario" json:"orcvo_valorcustounitario" toml:"orcvo_valorcustounitario" yaml:"orcvo_valorcustounitario"`
	OrcvoValorunitario      types.Decimal `boil:"orcvo_valorunitario" json:"orcvo_valorunitario" toml:"orcvo_valorunitario" yaml:"orcvo_valorunitario"`
	OrcvoQuantidade         types.Decimal `boil:"orcvo_quantidade" json:"orcvo_quantidade" toml:"orcvo_quantidade" yaml:"orcvo_quantidade"`
	OrcvoTotalcusto         types.Decimal `boil:"orcvo_totalcusto" json:"orcvo_totalcusto" toml:"orcvo_totalcusto" yaml:"orcvo_totalcusto"`
	OrcvoTotalitem          types.Decimal `boil:"orcvo_totalitem" json:"orcvo_totalitem" toml:"orcvo_totalitem" yaml:"orcvo_totalitem"`
	OrcvoDescricao          null.String   `boil:"orcvo_descricao" json:"orcvo_descricao,omitempty" toml:"orcvo_descricao" yaml:"orcvo_descricao,omitempty"`

	R *orcamentoVendaOperacionalR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L orcamentoVendaOperacionalL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OrcamentoVendaOperacionalColumns = struct {
	OrcvID                  string
	OrcvoItem               string
	DespID                  string
	OrcvoValorcustounitario string
	OrcvoValorunitario      string
	OrcvoQuantidade         string
	OrcvoTotalcusto         string
	OrcvoTotalitem          string
	OrcvoDescricao          string
}{
	OrcvID:                  "orcv_id",
	OrcvoItem:               "orcvo_item",
	DespID:                  "desp_id",
	OrcvoValorcustounitario: "orcvo_valorcustounitario",
	OrcvoValorunitario:      "orcvo_valorunitario",
	OrcvoQuantidade:         "orcvo_quantidade",
	OrcvoTotalcusto:         "orcvo_totalcusto",
	OrcvoTotalitem:          "orcvo_totalitem",
	OrcvoDescricao:          "orcvo_descricao",
}

var OrcamentoVendaOperacionalTableColumns = struct {
	OrcvID                  string
	OrcvoItem               string
	DespID                  string
	OrcvoValorcustounitario string
	OrcvoValorunitario      string
	OrcvoQuantidade         string
	OrcvoTotalcusto         string
	OrcvoTotalitem          string
	OrcvoDescricao          string
}{
	OrcvID:                  "orcamento_venda_operacional.orcv_id",
	OrcvoItem:               "orcamento_venda_operacional.orcvo_item",
	DespID:                  "orcamento_venda_operacional.desp_id",
	OrcvoValorcustounitario: "orcamento_venda_operacional.orcvo_valorcustounitario",
	OrcvoValorunitario:      "orcamento_venda_operacional.orcvo_valorunitario",
	OrcvoQuantidade:         "orcamento_venda_operacional.orcvo_quantidade",
	OrcvoTotalcusto:         "orcamento_venda_operacional.orcvo_totalcusto",
	OrcvoTotalitem:          "orcamento_venda_operacional.orcvo_totalitem",
	OrcvoDescricao:          "orcamento_venda_operacional.orcvo_descricao",
}

// Generated where

var OrcamentoVendaOperacionalWhere = struct {
	OrcvID                  whereHelperint
	OrcvoItem               whereHelperint
	DespID                  whereHelperint
	OrcvoValorcustounitario whereHelpertypes_Decimal
	OrcvoValorunitario      whereHelpertypes_Decimal
	OrcvoQuantidade         whereHelpertypes_Decimal
	OrcvoTotalcusto         whereHelpertypes_Decimal
	OrcvoTotalitem          whereHelpertypes_Decimal
	OrcvoDescricao          whereHelpernull_String
}{
	OrcvID:                  whereHelperint{field: "`orcamento_venda_operacional`.`orcv_id`"},
	OrcvoItem:               whereHelperint{field: "`orcamento_venda_operacional`.`orcvo_item`"},
	DespID:                  whereHelperint{field: "`orcamento_venda_operacional`.`desp_id`"},
	OrcvoValorcustounitario: whereHelpertypes_Decimal{field: "`orcamento_venda_operacional`.`orcvo_valorcustounitario`"},
	OrcvoValorunitario:      whereHelpertypes_Decimal{field: "`orcamento_venda_operacional`.`orcvo_valorunitario`"},
	OrcvoQuantidade:         whereHelpertypes_Decimal{field: "`orcamento_venda_operacional`.`orcvo_quantidade`"},
	OrcvoTotalcusto:         whereHelpertypes_Decimal{field: "`orcamento_venda_operacional`.`orcvo_totalcusto`"},
	OrcvoTotalitem:          whereHelpertypes_Decimal{field: "`orcamento_venda_operacional`.`orcvo_totalitem`"},
	OrcvoDescricao:          whereHelpernull_String{field: "`orcamento_venda_operacional`.`orcvo_descricao`"},
}

// OrcamentoVendaOperacionalRels is where relationship names are stored.
var OrcamentoVendaOperacionalRels = struct {
	Desp string
	Orcv string
}{
	Desp: "Desp",
	Orcv: "Orcv",
}

// orcamentoVendaOperacionalR is where relationships are stored.
type orcamentoVendaOperacionalR struct {
	Desp *Despesas       `boil:"Desp" json:"Desp" toml:"Desp" yaml:"Desp"`
	Orcv *OrcamentoVenda `boil:"Orcv" json:"Orcv" toml:"Orcv" yaml:"Orcv"`
}

// NewStruct creates a new relationship struct
func (*orcamentoVendaOperacionalR) NewStruct() *orcamentoVendaOperacionalR {
	return &orcamentoVendaOperacionalR{}
}

func (r *orcamentoVendaOperacionalR) GetDesp() *Despesas {
	if r == nil {
		return nil
	}
	return r.Desp
}

func (r *orcamentoVendaOperacionalR) GetOrcv() *OrcamentoVenda {
	if r == nil {
		return nil
	}
	return r.Orcv
}

// orcamentoVendaOperacionalL is where Load methods for each relationship are stored.
type orcamentoVendaOperacionalL struct{}

var (
	orcamentoVendaOperacionalAllColumns            = []string{"orcv_id", "orcvo_item", "desp_id", "orcvo_valorcustounitario", "orcvo_valorunitario", "orcvo_quantidade", "orcvo_totalcusto", "orcvo_totalitem", "orcvo_descricao"}
	orcamentoVendaOperacionalColumnsWithoutDefault = []string{"orcv_id", "orcvo_item", "desp_id", "orcvo_descricao"}
	orcamentoVendaOperacionalColumnsWithDefault    = []string{"orcvo_valorcustounitario", "orcvo_valorunitario", "orcvo_quantidade", "orcvo_totalcusto", "orcvo_totalitem"}
	orcamentoVendaOperacionalPrimaryKeyColumns     = []string{"orcv_id", "orcvo_item"}
	orcamentoVendaOperacionalGeneratedColumns      = []string{}
)

type (
	// OrcamentoVendaOperacionalSlice is an alias for a slice of pointers to OrcamentoVendaOperacional.
	// This should almost always be used instead of []OrcamentoVendaOperacional.
	OrcamentoVendaOperacionalSlice []*OrcamentoVendaOperacional
	// OrcamentoVendaOperacionalHook is the signature for custom OrcamentoVendaOperacional hook methods
	OrcamentoVendaOperacionalHook func(context.Context, boil.ContextExecutor, *OrcamentoVendaOperacional) error

	orcamentoVendaOperacionalQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	orcamentoVendaOperacionalType                 = reflect.TypeOf(&OrcamentoVendaOperacional{})
	orcamentoVendaOperacionalMapping              = queries.MakeStructMapping(orcamentoVendaOperacionalType)
	orcamentoVendaOperacionalPrimaryKeyMapping, _ = queries.BindMapping(orcamentoVendaOperacionalType, orcamentoVendaOperacionalMapping, orcamentoVendaOperacionalPrimaryKeyColumns)
	orcamentoVendaOperacionalInsertCacheMut       sync.RWMutex
	orcamentoVendaOperacionalInsertCache          = make(map[string]insertCache)
	orcamentoVendaOperacionalUpdateCacheMut       sync.RWMutex
	orcamentoVendaOperacionalUpdateCache          = make(map[string]updateCache)
	orcamentoVendaOperacionalUpsertCacheMut       sync.RWMutex
	orcamentoVendaOperacionalUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var orcamentoVendaOperacionalAfterSelectMu sync.Mutex
var orcamentoVendaOperacionalAfterSelectHooks []OrcamentoVendaOperacionalHook

var orcamentoVendaOperacionalBeforeInsertMu sync.Mutex
var orcamentoVendaOperacionalBeforeInsertHooks []OrcamentoVendaOperacionalHook
var orcamentoVendaOperacionalAfterInsertMu sync.Mutex
var orcamentoVendaOperacionalAfterInsertHooks []OrcamentoVendaOperacionalHook

var orcamentoVendaOperacionalBeforeUpdateMu sync.Mutex
var orcamentoVendaOperacionalBeforeUpdateHooks []OrcamentoVendaOperacionalHook
var orcamentoVendaOperacionalAfterUpdateMu sync.Mutex
var orcamentoVendaOperacionalAfterUpdateHooks []OrcamentoVendaOperacionalHook

var orcamentoVendaOperacionalBeforeDeleteMu sync.Mutex
var orcamentoVendaOperacionalBeforeDeleteHooks []OrcamentoVendaOperacionalHook
var orcamentoVendaOperacionalAfterDeleteMu sync.Mutex
var orcamentoVendaOperacionalAfterDeleteHooks []OrcamentoVendaOperacionalHook

var orcamentoVendaOperacionalBeforeUpsertMu sync.Mutex
var orcamentoVendaOperacionalBeforeUpsertHooks []OrcamentoVendaOperacionalHook
var orcamentoVendaOperacionalAfterUpsertMu sync.Mutex
var orcamentoVendaOperacionalAfterUpsertHooks []OrcamentoVendaOperacionalHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *OrcamentoVendaOperacional) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *OrcamentoVendaOperacional) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *OrcamentoVendaOperacional) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *OrcamentoVendaOperacional) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *OrcamentoVendaOperacional) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *OrcamentoVendaOperacional) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *OrcamentoVendaOperacional) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *OrcamentoVendaOperacional) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *OrcamentoVendaOperacional) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orcamentoVendaOperacionalAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOrcamentoVendaOperacionalHook registers your hook function for all future operations.
func AddOrcamentoVendaOperacionalHook(hookPoint boil.HookPoint, orcamentoVendaOperacionalHook OrcamentoVendaOperacionalHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		orcamentoVendaOperacionalAfterSelectMu.Lock()
		orcamentoVendaOperacionalAfterSelectHooks = append(orcamentoVendaOperacionalAfterSelectHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		orcamentoVendaOperacionalBeforeInsertMu.Lock()
		orcamentoVendaOperacionalBeforeInsertHooks = append(orcamentoVendaOperacionalBeforeInsertHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		orcamentoVendaOperacionalAfterInsertMu.Lock()
		orcamentoVendaOperacionalAfterInsertHooks = append(orcamentoVendaOperacionalAfterInsertHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		orcamentoVendaOperacionalBeforeUpdateMu.Lock()
		orcamentoVendaOperacionalBeforeUpdateHooks = append(orcamentoVendaOperacionalBeforeUpdateHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		orcamentoVendaOperacionalAfterUpdateMu.Lock()
		orcamentoVendaOperacionalAfterUpdateHooks = append(orcamentoVendaOperacionalAfterUpdateHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		orcamentoVendaOperacionalBeforeDeleteMu.Lock()
		orcamentoVendaOperacionalBeforeDeleteHooks = append(orcamentoVendaOperacionalBeforeDeleteHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		orcamentoVendaOperacionalAfterDeleteMu.Lock()
		orcamentoVendaOperacionalAfterDeleteHooks = append(orcamentoVendaOperacionalAfterDeleteHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		orcamentoVendaOperacionalBeforeUpsertMu.Lock()
		orcamentoVendaOperacionalBeforeUpsertHooks = append(orcamentoVendaOperacionalBeforeUpsertHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		orcamentoVendaOperacionalAfterUpsertMu.Lock()
		orcamentoVendaOperacionalAfterUpsertHooks = append(orcamentoVendaOperacionalAfterUpsertHooks, orcamentoVendaOperacionalHook)
		orcamentoVendaOperacionalAfterUpsertMu.Unlock()
	}
}

// One returns a single orcamentoVendaOperacional record from the query.
func (q orcamentoVendaOperacionalQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OrcamentoVendaOperacional, error) {
	o := &OrcamentoVendaOperacional{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for orcamento_venda_operacional")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all OrcamentoVendaOperacional records from the query.
func (q orcamentoVendaOperacionalQuery) All(ctx context.Context, exec boil.ContextExecutor) (OrcamentoVendaOperacionalSlice, error) {
	var o []*OrcamentoVendaOperacional

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to OrcamentoVendaOperacional slice")
	}

	if len(orcamentoVendaOperacionalAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all OrcamentoVendaOperacional records in the query.
func (q orcamentoVendaOperacionalQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count orcamento_venda_operacional rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q orcamentoVendaOperacionalQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if orcamento_venda_operacional exists")
	}

	return count > 0, nil
}

// Desp pointed to by the foreign key.
func (o *OrcamentoVendaOperacional) Desp(mods ...qm.QueryMod) despesasQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`desp_id` = ?", o.DespID),
	}

	queryMods = append(queryMods, mods...)

	return Despesas(queryMods...)
}

// Orcv pointed to by the foreign key.
func (o *OrcamentoVendaOperacional) Orcv(mods ...qm.QueryMod) orcamentoVendaQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`orcv_id` = ?", o.OrcvID),
	}

	queryMods = append(queryMods, mods...)

	return OrcamentoVendas(queryMods...)
}

// LoadDesp allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (orcamentoVendaOperacionalL) LoadDesp(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrcamentoVendaOperacional interface{}, mods queries.Applicator) error {
	var slice []*OrcamentoVendaOperacional
	var object *OrcamentoVendaOperacional

	if singular {
		var ok bool
		object, ok = maybeOrcamentoVendaOperacional.(*OrcamentoVendaOperacional)
		if !ok {
			object = new(OrcamentoVendaOperacional)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOrcamentoVendaOperacional)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOrcamentoVendaOperacional))
			}
		}
	} else {
		s, ok := maybeOrcamentoVendaOperacional.(*[]*OrcamentoVendaOperacional)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOrcamentoVendaOperacional)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOrcamentoVendaOperacional))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &orcamentoVendaOperacionalR{}
		}
		args[object.DespID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &orcamentoVendaOperacionalR{}
			}

			args[obj.DespID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`despesas`),
		qm.WhereIn(`despesas.desp_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Despesas")
	}

	var resultSlice []*Despesas
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Despesas")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for despesas")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for despesas")
	}

	if len(despesasAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Desp = foreign
		if foreign.R == nil {
			foreign.R = &despesasR{}
		}
		foreign.R.DespOrcamentoVendaOperacionals = append(foreign.R.DespOrcamentoVendaOperacionals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DespID == foreign.DespID {
				local.R.Desp = foreign
				if foreign.R == nil {
					foreign.R = &despesasR{}
				}
				foreign.R.DespOrcamentoVendaOperacionals = append(foreign.R.DespOrcamentoVendaOperacionals, local)
				break
			}
		}
	}

	return nil
}

// LoadOrcv allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (orcamentoVendaOperacionalL) LoadOrcv(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrcamentoVendaOperacional interface{}, mods queries.Applicator) error {
	var slice []*OrcamentoVendaOperacional
	var object *OrcamentoVendaOperacional

	if singular {
		var ok bool
		object, ok = maybeOrcamentoVendaOperacional.(*OrcamentoVendaOperacional)
		if !ok {
			object = new(OrcamentoVendaOperacional)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOrcamentoVendaOperacional)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOrcamentoVendaOperacional))
			}
		}
	} else {
		s, ok := maybeOrcamentoVendaOperacional.(*[]*OrcamentoVendaOperacional)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOrcamentoVendaOperacional)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOrcamentoVendaOperacional))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &orcamentoVendaOperacionalR{}
		}
		args[object.OrcvID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &orcamentoVendaOperacionalR{}
			}

			args[obj.OrcvID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`orcamento_venda`),
		qm.WhereIn(`orcamento_venda.orcv_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load OrcamentoVenda")
	}

	var resultSlice []*OrcamentoVenda
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice OrcamentoVenda")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for orcamento_venda")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for orcamento_venda")
	}

	if len(orcamentoVendaAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Orcv = foreign
		if foreign.R == nil {
			foreign.R = &orcamentoVendaR{}
		}
		foreign.R.OrcvOrcamentoVendaOperacionals = append(foreign.R.OrcvOrcamentoVendaOperacionals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.OrcvID == foreign.OrcvID {
				local.R.Orcv = foreign
				if foreign.R == nil {
					foreign.R = &orcamentoVendaR{}
				}
				foreign.R.OrcvOrcamentoVendaOperacionals = append(foreign.R.OrcvOrcamentoVendaOperacionals, local)
				break
			}
		}
	}

	return nil
}

// SetDesp of the orcamentoVendaOperacional to the related item.
// Sets o.R.Desp to related.
// Adds o to related.R.DespOrcamentoVendaOperacionals.
func (o *OrcamentoVendaOperacional) SetDesp(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Despesas) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `orcamento_venda_operacional` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"desp_id"}),
		strmangle.WhereClause("`", "`", 0, orcamentoVendaOperacionalPrimaryKeyColumns),
	)
	values := []interface{}{related.DespID, o.OrcvID, o.OrcvoItem}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DespID = related.DespID
	if o.R == nil {
		o.R = &orcamentoVendaOperacionalR{
			Desp: related,
		}
	} else {
		o.R.Desp = related
	}

	if related.R == nil {
		related.R = &despesasR{
			DespOrcamentoVendaOperacionals: OrcamentoVendaOperacionalSlice{o},
		}
	} else {
		related.R.DespOrcamentoVendaOperacionals = append(related.R.DespOrcamentoVendaOperacionals, o)
	}

	return nil
}

// SetOrcv of the orcamentoVendaOperacional to the related item.
// Sets o.R.Orcv to related.
// Adds o to related.R.OrcvOrcamentoVendaOperacionals.
func (o *OrcamentoVendaOperacional) SetOrcv(ctx context.Context, exec boil.ContextExecutor, insert bool, related *OrcamentoVenda) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `orcamento_venda_operacional` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"orcv_id"}),
		strmangle.WhereClause("`", "`", 0, orcamentoVendaOperacionalPrimaryKeyColumns),
	)
	values := []interface{}{related.OrcvID, o.OrcvID, o.OrcvoItem}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.OrcvID = related.OrcvID
	if o.R == nil {
		o.R = &orcamentoVendaOperacionalR{
			Orcv: related,
		}
	} else {
		o.R.Orcv = related
	}

	if related.R == nil {
		related.R = &orcamentoVendaR{
			OrcvOrcamentoVendaOperacionals: OrcamentoVendaOperacionalSlice{o},
		}
	} else {
		related.R.OrcvOrcamentoVendaOperacionals = append(related.R.OrcvOrcamentoVendaOperacionals, o)
	}

	return nil
}

// OrcamentoVendaOperacionals retrieves all the records using an executor.
func OrcamentoVendaOperacionals(mods ...qm.QueryMod) orcamentoVendaOperacionalQuery {
	mods = append(mods, qm.From("`orcamento_venda_operacional`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`orcamento_venda_operacional`.*"})
	}

	return orcamentoVendaOperacionalQuery{q}
}

// FindOrcamentoVendaOperacional retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOrcamentoVendaOperacional(ctx context.Context, exec boil.ContextExecutor, orcvID int, orcvoItem int, selectCols ...string) (*OrcamentoVendaOperacional, error) {
	orcamentoVendaOperacionalObj := &OrcamentoVendaOperacional{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `orcamento_venda_operacional` where `orcv_id`=? AND `orcvo_item`=?", sel,
	)

	q := queries.Raw(query, orcvID, orcvoItem)

	err := q.Bind(ctx, exec, orcamentoVendaOperacionalObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from orcamento_venda_operacional")
	}

	if err = orcamentoVendaOperacionalObj.doAfterSelectHooks(ctx, exec); err != nil {
		return orcamentoVendaOperacionalObj, err
	}

	return orcamentoVendaOperacionalObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OrcamentoVendaOperacional) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no orcamento_venda_operacional provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(orcamentoVendaOperacionalColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	orcamentoVendaOperacionalInsertCacheMut.RLock()
	cache, cached := orcamentoVendaOperacionalInsertCache[key]
	orcamentoVendaOperacionalInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			orcamentoVendaOperacionalAllColumns,
			orcamentoVendaOperacionalColumnsWithDefault,
			orcamentoVendaOperacionalColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(orcamentoVendaOperacionalType, orcamentoVendaOperacionalMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(orcamentoVendaOperacionalType, orcamentoVendaOperacionalMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `orcamento_venda_operacional` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `orcamento_venda_operacional` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `orcamento_venda_operacional` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, orcamentoVendaOperacionalPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into orcamento_venda_operacional")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.OrcvID,
		o.OrcvoItem,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for orcamento_venda_operacional")
	}

CacheNoHooks:
	if !cached {
		orcamentoVendaOperacionalInsertCacheMut.Lock()
		orcamentoVendaOperacionalInsertCache[key] = cache
		orcamentoVendaOperacionalInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the OrcamentoVendaOperacional.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OrcamentoVendaOperacional) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	orcamentoVendaOperacionalUpdateCacheMut.RLock()
	cache, cached := orcamentoVendaOperacionalUpdateCache[key]
	orcamentoVendaOperacionalUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			orcamentoVendaOperacionalAllColumns,
			orcamentoVendaOperacionalPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update orcamento_venda_operacional, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `orcamento_venda_operacional` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, orcamentoVendaOperacionalPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(orcamentoVendaOperacionalType, orcamentoVendaOperacionalMapping, append(wl, orcamentoVendaOperacionalPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update orcamento_venda_operacional row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for orcamento_venda_operacional")
	}

	if !cached {
		orcamentoVendaOperacionalUpdateCacheMut.Lock()
		orcamentoVendaOperacionalUpdateCache[key] = cache
		orcamentoVendaOperacionalUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q orcamentoVendaOperacionalQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for orcamento_venda_operacional")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for orcamento_venda_operacional")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OrcamentoVendaOperacionalSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), orcamentoVendaOperacionalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `orcamento_venda_operacional` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, orcamentoVendaOperacionalPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in orcamentoVendaOperacional slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all orcamentoVendaOperacional")
	}
	return rowsAff, nil
}

var mySQLOrcamentoVendaOperacionalUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OrcamentoVendaOperacional) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no orcamento_venda_operacional provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(orcamentoVendaOperacionalColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLOrcamentoVendaOperacionalUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	orcamentoVendaOperacionalUpsertCacheMut.RLock()
	cache, cached := orcamentoVendaOperacionalUpsertCache[key]
	orcamentoVendaOperacionalUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			orcamentoVendaOperacionalAllColumns,
			orcamentoVendaOperacionalColumnsWithDefault,
			orcamentoVendaOperacionalColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			orcamentoVendaOperacionalAllColumns,
			orcamentoVendaOperacionalPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert orcamento_venda_operacional, could not build update column list")
		}

		ret := strmangle.SetComplement(orcamentoVendaOperacionalAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`orcamento_venda_operacional`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `orcamento_venda_operacional` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(orcamentoVendaOperacionalType, orcamentoVendaOperacionalMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(orcamentoVendaOperacionalType, orcamentoVendaOperacionalMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for orcamento_venda_operacional")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(orcamentoVendaOperacionalType, orcamentoVendaOperacionalMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for orcamento_venda_operacional")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for orcamento_venda_operacional")
	}

CacheNoHooks:
	if !cached {
		orcamentoVendaOperacionalUpsertCacheMut.Lock()
		orcamentoVendaOperacionalUpsertCache[key] = cache
		orcamentoVendaOperacionalUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single OrcamentoVendaOperacional record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OrcamentoVendaOperacional) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no OrcamentoVendaOperacional provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), orcamentoVendaOperacionalPrimaryKeyMapping)
	sql := "DELETE FROM `orcamento_venda_operacional` WHERE `orcv_id`=? AND `orcvo_item`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from orcamento_venda_operacional")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for orcamento_venda_operacional")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q orcamentoVendaOperacionalQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no orcamentoVendaOperacionalQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from orcamento_venda_operacional")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for orcamento_venda_operacional")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OrcamentoVendaOperacionalSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(orcamentoVendaOperacionalBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), orcamentoVendaOperacionalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `orcamento_venda_operacional` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, orcamentoVendaOperacionalPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from orcamentoVendaOperacional slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for orcamento_venda_operacional")
	}

	if len(orcamentoVendaOperacionalAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OrcamentoVendaOperacional) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOrcamentoVendaOperacional(ctx, exec, o.OrcvID, o.OrcvoItem)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OrcamentoVendaOperacionalSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OrcamentoVendaOperacionalSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), orcamentoVendaOperacionalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `orcamento_venda_operacional`.* FROM `orcamento_venda_operacional` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, orcamentoVendaOperacionalPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in OrcamentoVendaOperacionalSlice")
	}

	*o = slice

	return nil
}

// OrcamentoVendaOperacionalExists checks if the OrcamentoVendaOperacional row exists.
func OrcamentoVendaOperacionalExists(ctx context.Context, exec boil.ContextExecutor, orcvID int, orcvoItem int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `orcamento_venda_operacional` where `orcv_id`=? AND `orcvo_item`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, orcvID, orcvoItem)
	}
	row := exec.QueryRowContext(ctx, sql, orcvID, orcvoItem)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if orcamento_venda_operacional exists")
	}

	return exists, nil
}

// Exists checks if the OrcamentoVendaOperacional row exists.
func (o *OrcamentoVendaOperacional) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OrcamentoVendaOperacionalExists(ctx, exec, o.OrcvID, o.OrcvoItem)
}
