// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Sistema is an object representing the database table.
type Sistema struct {
	SisID              int         `boil:"sis_id" json:"sis_id" toml:"sis_id" yaml:"sis_id"`
	EmfID              null.Int    `boil:"emf_id" json:"emf_id,omitempty" toml:"emf_id" yaml:"emf_id,omitempty"`
	SisCodigo          int         `boil:"sis_codigo" json:"sis_codigo" toml:"sis_codigo" yaml:"sis_codigo"`
	SisDescricao       string      `boil:"sis_descricao" json:"sis_descricao" toml:"sis_descricao" yaml:"sis_descricao"`
	SisDescricaofiname null.String `boil:"sis_descricaofiname" json:"sis_descricaofiname,omitempty" toml:"sis_descricaofiname" yaml:"sis_descricaofiname,omitempty"`
	SisSituacao        int16       `boil:"sis_situacao" json:"sis_situacao" toml:"sis_situacao" yaml:"sis_situacao"`

	R *sistemaR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sistemaL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SistemaColumns = struct {
	SisID              string
	EmfID              string
	SisCodigo          string
	SisDescricao       string
	SisDescricaofiname string
	SisSituacao        string
}{
	SisID:              "sis_id",
	EmfID:              "emf_id",
	SisCodigo:          "sis_codigo",
	SisDescricao:       "sis_descricao",
	SisDescricaofiname: "sis_descricaofiname",
	SisSituacao:        "sis_situacao",
}

var SistemaTableColumns = struct {
	SisID              string
	EmfID              string
	SisCodigo          string
	SisDescricao       string
	SisDescricaofiname string
	SisSituacao        string
}{
	SisID:              "sistema.sis_id",
	EmfID:              "sistema.emf_id",
	SisCodigo:          "sistema.sis_codigo",
	SisDescricao:       "sistema.sis_descricao",
	SisDescricaofiname: "sistema.sis_descricaofiname",
	SisSituacao:        "sistema.sis_situacao",
}

// Generated where

var SistemaWhere = struct {
	SisID              whereHelperint
	EmfID              whereHelpernull_Int
	SisCodigo          whereHelperint
	SisDescricao       whereHelperstring
	SisDescricaofiname whereHelpernull_String
	SisSituacao        whereHelperint16
}{
	SisID:              whereHelperint{field: "`sistema`.`sis_id`"},
	EmfID:              whereHelpernull_Int{field: "`sistema`.`emf_id`"},
	SisCodigo:          whereHelperint{field: "`sistema`.`sis_codigo`"},
	SisDescricao:       whereHelperstring{field: "`sistema`.`sis_descricao`"},
	SisDescricaofiname: whereHelpernull_String{field: "`sistema`.`sis_descricaofiname`"},
	SisSituacao:        whereHelperint16{field: "`sistema`.`sis_situacao`"},
}

// SistemaRels is where relationship names are stored.
var SistemaRels = struct {
	Emf         string
	SisProdutos string
}{
	Emf:         "Emf",
	SisProdutos: "SisProdutos",
}

// sistemaR is where relationships are stored.
type sistemaR struct {
	Emf         *EmpresaFilial `boil:"Emf" json:"Emf" toml:"Emf" yaml:"Emf"`
	SisProdutos ProdutoSlice   `boil:"SisProdutos" json:"SisProdutos" toml:"SisProdutos" yaml:"SisProdutos"`
}

// NewStruct creates a new relationship struct
func (*sistemaR) NewStruct() *sistemaR {
	return &sistemaR{}
}

func (r *sistemaR) GetEmf() *EmpresaFilial {
	if r == nil {
		return nil
	}
	return r.Emf
}

func (r *sistemaR) GetSisProdutos() ProdutoSlice {
	if r == nil {
		return nil
	}
	return r.SisProdutos
}

// sistemaL is where Load methods for each relationship are stored.
type sistemaL struct{}

var (
	sistemaAllColumns            = []string{"sis_id", "emf_id", "sis_codigo", "sis_descricao", "sis_descricaofiname", "sis_situacao"}
	sistemaColumnsWithoutDefault = []string{"sis_id", "emf_id", "sis_codigo", "sis_descricao", "sis_descricaofiname"}
	sistemaColumnsWithDefault    = []string{"sis_situacao"}
	sistemaPrimaryKeyColumns     = []string{"sis_id"}
	sistemaGeneratedColumns      = []string{}
)

type (
	// SistemaSlice is an alias for a slice of pointers to Sistema.
	// This should almost always be used instead of []Sistema.
	SistemaSlice []*Sistema
	// SistemaHook is the signature for custom Sistema hook methods
	SistemaHook func(context.Context, boil.ContextExecutor, *Sistema) error

	sistemaQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sistemaType                 = reflect.TypeOf(&Sistema{})
	sistemaMapping              = queries.MakeStructMapping(sistemaType)
	sistemaPrimaryKeyMapping, _ = queries.BindMapping(sistemaType, sistemaMapping, sistemaPrimaryKeyColumns)
	sistemaInsertCacheMut       sync.RWMutex
	sistemaInsertCache          = make(map[string]insertCache)
	sistemaUpdateCacheMut       sync.RWMutex
	sistemaUpdateCache          = make(map[string]updateCache)
	sistemaUpsertCacheMut       sync.RWMutex
	sistemaUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var sistemaAfterSelectMu sync.Mutex
var sistemaAfterSelectHooks []SistemaHook

var sistemaBeforeInsertMu sync.Mutex
var sistemaBeforeInsertHooks []SistemaHook
var sistemaAfterInsertMu sync.Mutex
var sistemaAfterInsertHooks []SistemaHook

var sistemaBeforeUpdateMu sync.Mutex
var sistemaBeforeUpdateHooks []SistemaHook
var sistemaAfterUpdateMu sync.Mutex
var sistemaAfterUpdateHooks []SistemaHook

var sistemaBeforeDeleteMu sync.Mutex
var sistemaBeforeDeleteHooks []SistemaHook
var sistemaAfterDeleteMu sync.Mutex
var sistemaAfterDeleteHooks []SistemaHook

var sistemaBeforeUpsertMu sync.Mutex
var sistemaBeforeUpsertHooks []SistemaHook
var sistemaAfterUpsertMu sync.Mutex
var sistemaAfterUpsertHooks []SistemaHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Sistema) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Sistema) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Sistema) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Sistema) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Sistema) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Sistema) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Sistema) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Sistema) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Sistema) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sistemaAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSistemaHook registers your hook function for all future operations.
func AddSistemaHook(hookPoint boil.HookPoint, sistemaHook SistemaHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		sistemaAfterSelectMu.Lock()
		sistemaAfterSelectHooks = append(sistemaAfterSelectHooks, sistemaHook)
		sistemaAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		sistemaBeforeInsertMu.Lock()
		sistemaBeforeInsertHooks = append(sistemaBeforeInsertHooks, sistemaHook)
		sistemaBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		sistemaAfterInsertMu.Lock()
		sistemaAfterInsertHooks = append(sistemaAfterInsertHooks, sistemaHook)
		sistemaAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		sistemaBeforeUpdateMu.Lock()
		sistemaBeforeUpdateHooks = append(sistemaBeforeUpdateHooks, sistemaHook)
		sistemaBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		sistemaAfterUpdateMu.Lock()
		sistemaAfterUpdateHooks = append(sistemaAfterUpdateHooks, sistemaHook)
		sistemaAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		sistemaBeforeDeleteMu.Lock()
		sistemaBeforeDeleteHooks = append(sistemaBeforeDeleteHooks, sistemaHook)
		sistemaBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		sistemaAfterDeleteMu.Lock()
		sistemaAfterDeleteHooks = append(sistemaAfterDeleteHooks, sistemaHook)
		sistemaAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		sistemaBeforeUpsertMu.Lock()
		sistemaBeforeUpsertHooks = append(sistemaBeforeUpsertHooks, sistemaHook)
		sistemaBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		sistemaAfterUpsertMu.Lock()
		sistemaAfterUpsertHooks = append(sistemaAfterUpsertHooks, sistemaHook)
		sistemaAfterUpsertMu.Unlock()
	}
}

// One returns a single sistema record from the query.
func (q sistemaQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Sistema, error) {
	o := &Sistema{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for sistema")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Sistema records from the query.
func (q sistemaQuery) All(ctx context.Context, exec boil.ContextExecutor) (SistemaSlice, error) {
	var o []*Sistema

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Sistema slice")
	}

	if len(sistemaAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Sistema records in the query.
func (q sistemaQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count sistema rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sistemaQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if sistema exists")
	}

	return count > 0, nil
}

// Emf pointed to by the foreign key.
func (o *Sistema) Emf(mods ...qm.QueryMod) empresaFilialQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`emf_id` = ?", o.EmfID),
	}

	queryMods = append(queryMods, mods...)

	return EmpresaFilials(queryMods...)
}

// SisProdutos retrieves all the produto's Produtos with an executor via sis_id column.
func (o *Sistema) SisProdutos(mods ...qm.QueryMod) produtoQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`produto`.`sis_id`=?", o.SisID),
	)

	return Produtos(queryMods...)
}

// LoadEmf allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sistemaL) LoadEmf(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSistema interface{}, mods queries.Applicator) error {
	var slice []*Sistema
	var object *Sistema

	if singular {
		var ok bool
		object, ok = maybeSistema.(*Sistema)
		if !ok {
			object = new(Sistema)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSistema)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSistema))
			}
		}
	} else {
		s, ok := maybeSistema.(*[]*Sistema)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSistema)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSistema))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &sistemaR{}
		}
		if !queries.IsNil(object.EmfID) {
			args[object.EmfID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sistemaR{}
			}

			if !queries.IsNil(obj.EmfID) {
				args[obj.EmfID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`empresa_filial`),
		qm.WhereIn(`empresa_filial.emf_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load EmpresaFilial")
	}

	var resultSlice []*EmpresaFilial
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice EmpresaFilial")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for empresa_filial")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for empresa_filial")
	}

	if len(empresaFilialAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Emf = foreign
		if foreign.R == nil {
			foreign.R = &empresaFilialR{}
		}
		foreign.R.EmfSistemas = append(foreign.R.EmfSistemas, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.EmfID, foreign.EmfID) {
				local.R.Emf = foreign
				if foreign.R == nil {
					foreign.R = &empresaFilialR{}
				}
				foreign.R.EmfSistemas = append(foreign.R.EmfSistemas, local)
				break
			}
		}
	}

	return nil
}

// LoadSisProdutos allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (sistemaL) LoadSisProdutos(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSistema interface{}, mods queries.Applicator) error {
	var slice []*Sistema
	var object *Sistema

	if singular {
		var ok bool
		object, ok = maybeSistema.(*Sistema)
		if !ok {
			object = new(Sistema)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSistema)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSistema))
			}
		}
	} else {
		s, ok := maybeSistema.(*[]*Sistema)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSistema)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSistema))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &sistemaR{}
		}
		args[object.SisID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sistemaR{}
			}
			args[obj.SisID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`produto`),
		qm.WhereIn(`produto.sis_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load produto")
	}

	var resultSlice []*Produto
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice produto")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on produto")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for produto")
	}

	if len(produtoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SisProdutos = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &produtoR{}
			}
			foreign.R.Sis = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.SisID, foreign.SisID) {
				local.R.SisProdutos = append(local.R.SisProdutos, foreign)
				if foreign.R == nil {
					foreign.R = &produtoR{}
				}
				foreign.R.Sis = local
				break
			}
		}
	}

	return nil
}

// SetEmf of the sistema to the related item.
// Sets o.R.Emf to related.
// Adds o to related.R.EmfSistemas.
func (o *Sistema) SetEmf(ctx context.Context, exec boil.ContextExecutor, insert bool, related *EmpresaFilial) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `sistema` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"emf_id"}),
		strmangle.WhereClause("`", "`", 0, sistemaPrimaryKeyColumns),
	)
	values := []interface{}{related.EmfID, o.SisID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.EmfID, related.EmfID)
	if o.R == nil {
		o.R = &sistemaR{
			Emf: related,
		}
	} else {
		o.R.Emf = related
	}

	if related.R == nil {
		related.R = &empresaFilialR{
			EmfSistemas: SistemaSlice{o},
		}
	} else {
		related.R.EmfSistemas = append(related.R.EmfSistemas, o)
	}

	return nil
}

// RemoveEmf relationship.
// Sets o.R.Emf to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Sistema) RemoveEmf(ctx context.Context, exec boil.ContextExecutor, related *EmpresaFilial) error {
	var err error

	queries.SetScanner(&o.EmfID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("emf_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Emf = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.EmfSistemas {
		if queries.Equal(o.EmfID, ri.EmfID) {
			continue
		}

		ln := len(related.R.EmfSistemas)
		if ln > 1 && i < ln-1 {
			related.R.EmfSistemas[i] = related.R.EmfSistemas[ln-1]
		}
		related.R.EmfSistemas = related.R.EmfSistemas[:ln-1]
		break
	}
	return nil
}

// AddSisProdutos adds the given related objects to the existing relationships
// of the sistema, optionally inserting them as new records.
// Appends related to o.R.SisProdutos.
// Sets related.R.Sis appropriately.
func (o *Sistema) AddSisProdutos(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Produto) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.SisID, o.SisID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `produto` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"sis_id"}),
				strmangle.WhereClause("`", "`", 0, produtoPrimaryKeyColumns),
			)
			values := []interface{}{o.SisID, rel.ProID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.SisID, o.SisID)
		}
	}

	if o.R == nil {
		o.R = &sistemaR{
			SisProdutos: related,
		}
	} else {
		o.R.SisProdutos = append(o.R.SisProdutos, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &produtoR{
				Sis: o,
			}
		} else {
			rel.R.Sis = o
		}
	}
	return nil
}

// SetSisProdutos removes all previously related items of the
// sistema replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Sis's SisProdutos accordingly.
// Replaces o.R.SisProdutos with related.
// Sets related.R.Sis's SisProdutos accordingly.
func (o *Sistema) SetSisProdutos(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Produto) error {
	query := "update `produto` set `sis_id` = null where `sis_id` = ?"
	values := []interface{}{o.SisID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.SisProdutos {
			queries.SetScanner(&rel.SisID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Sis = nil
		}
		o.R.SisProdutos = nil
	}

	return o.AddSisProdutos(ctx, exec, insert, related...)
}

// RemoveSisProdutos relationships from objects passed in.
// Removes related items from R.SisProdutos (uses pointer comparison, removal does not keep order)
// Sets related.R.Sis.
func (o *Sistema) RemoveSisProdutos(ctx context.Context, exec boil.ContextExecutor, related ...*Produto) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.SisID, nil)
		if rel.R != nil {
			rel.R.Sis = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("sis_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.SisProdutos {
			if rel != ri {
				continue
			}

			ln := len(o.R.SisProdutos)
			if ln > 1 && i < ln-1 {
				o.R.SisProdutos[i] = o.R.SisProdutos[ln-1]
			}
			o.R.SisProdutos = o.R.SisProdutos[:ln-1]
			break
		}
	}

	return nil
}

// Sistemas retrieves all the records using an executor.
func Sistemas(mods ...qm.QueryMod) sistemaQuery {
	mods = append(mods, qm.From("`sistema`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`sistema`.*"})
	}

	return sistemaQuery{q}
}

// FindSistema retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSistema(ctx context.Context, exec boil.ContextExecutor, sisID int, selectCols ...string) (*Sistema, error) {
	sistemaObj := &Sistema{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `sistema` where `sis_id`=?", sel,
	)

	q := queries.Raw(query, sisID)

	err := q.Bind(ctx, exec, sistemaObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from sistema")
	}

	if err = sistemaObj.doAfterSelectHooks(ctx, exec); err != nil {
		return sistemaObj, err
	}

	return sistemaObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Sistema) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sistema provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sistemaColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sistemaInsertCacheMut.RLock()
	cache, cached := sistemaInsertCache[key]
	sistemaInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sistemaAllColumns,
			sistemaColumnsWithDefault,
			sistemaColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sistemaType, sistemaMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sistemaType, sistemaMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `sistema` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `sistema` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `sistema` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, sistemaPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into sistema")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.SisID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sistema")
	}

CacheNoHooks:
	if !cached {
		sistemaInsertCacheMut.Lock()
		sistemaInsertCache[key] = cache
		sistemaInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Sistema.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Sistema) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sistemaUpdateCacheMut.RLock()
	cache, cached := sistemaUpdateCache[key]
	sistemaUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sistemaAllColumns,
			sistemaPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update sistema, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `sistema` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, sistemaPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sistemaType, sistemaMapping, append(wl, sistemaPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update sistema row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for sistema")
	}

	if !cached {
		sistemaUpdateCacheMut.Lock()
		sistemaUpdateCache[key] = cache
		sistemaUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q sistemaQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for sistema")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for sistema")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SistemaSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sistemaPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `sistema` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sistemaPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in sistema slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all sistema")
	}
	return rowsAff, nil
}

var mySQLSistemaUniqueColumns = []string{
	"sis_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Sistema) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sistema provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sistemaColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSistemaUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sistemaUpsertCacheMut.RLock()
	cache, cached := sistemaUpsertCache[key]
	sistemaUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			sistemaAllColumns,
			sistemaColumnsWithDefault,
			sistemaColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			sistemaAllColumns,
			sistemaPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert sistema, could not build update column list")
		}

		ret := strmangle.SetComplement(sistemaAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`sistema`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `sistema` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(sistemaType, sistemaMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sistemaType, sistemaMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for sistema")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(sistemaType, sistemaMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for sistema")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sistema")
	}

CacheNoHooks:
	if !cached {
		sistemaUpsertCacheMut.Lock()
		sistemaUpsertCache[key] = cache
		sistemaUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Sistema record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Sistema) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Sistema provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sistemaPrimaryKeyMapping)
	sql := "DELETE FROM `sistema` WHERE `sis_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from sistema")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for sistema")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sistemaQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no sistemaQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sistema")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sistema")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SistemaSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sistemaBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sistemaPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `sistema` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sistemaPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sistema slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sistema")
	}

	if len(sistemaAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Sistema) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSistema(ctx, exec, o.SisID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SistemaSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SistemaSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sistemaPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `sistema`.* FROM `sistema` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sistemaPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SistemaSlice")
	}

	*o = slice

	return nil
}

// SistemaExists checks if the Sistema row exists.
func SistemaExists(ctx context.Context, exec boil.ContextExecutor, sisID int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `sistema` where `sis_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, sisID)
	}
	row := exec.QueryRowContext(ctx, sql, sisID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if sistema exists")
	}

	return exists, nil
}

// Exists checks if the Sistema row exists.
func (o *Sistema) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SistemaExists(ctx, exec, o.SisID)
}
